CREATE SEQUENCE YCAST_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YCAST_CURRENT
(
    YCASTID BIGINT NOT NULL,
    IEDNAME VARGRAPHIC(100 CODEUNITS16),
    COLTIME TIMESTAMP,
    UA      DECIMAL(31, 2),
    UB      DECIMAL(31, 2),
    UC      DECIMAL(31, 2),
    IA      DECIMAL(31, 2),
    IB      DECIMAL(31, 2),
    IC      DECIMAL(31, 2)
);


CREATE SEQUENCE YCAST_LOG_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;

CREATE TABLE MAXIMO.YCAST_LOG
(
    YCASTID BIGINT NOT NULL,
    IEDNAME VARGRAPHIC(100 CODEUNITS16),
    COLTIME TIMESTAMP,
    UA      DECIMAL(31, 2),
    UB      DECIMAL(31, 2),
    UC      DECIMAL(31, 2),
    IA      DECIMAL(31, 2),
    IB      DECIMAL(31, 2),
    IC      DECIMAL(31, 2)
);