-- 单台变压器运行健康状况得分-季度
CREATE TABLE MAXIMO.RE_TRANS_HEALTH_QUARTER
(
    RETRANSFORMERHEALTHQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    SCORELEVEL        VARGRAPHIC(50),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERHEALTHQUARTERID)
);



-- 单台变压器运行健康状况得分-年度
CREATE TABLE MAXIMO.RE_TRANS_HEALTH_YEAR
(
    RETRANSFORMERHEALTHYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    SCORELEVEL        VARGRAPHIC(50),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERHEALTHYEARID)
);


-- 单台变压器运行健康状况得分对比-季度
CREATE TABLE MAXIMO.RE_TRANS_HEA_COM_QUARTER
(
    RETRANSHEACOMQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC     VARGRAPHIC(100),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    COMPARISON        VARGRAPHIC(50),
    RATIO             DECIMAL(8, 4),
    PRIMARY KEY (RETRANSHEACOMQUARTERID)
);


-- 单台变压器运行健康状况得分对比-年度
CREATE TABLE MAXIMO.RE_TRANS_HEA_COM_YEAR
(
    RETRANSHEACOMYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC     VARGRAPHIC(100),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    COMPARISON        VARGRAPHIC(50),
    RATIO             DECIMAL(8, 4),
    PRIMARY KEY (RETRANSHEACOMYEARID)
);
