-- 整体变压器运行健康状况得分-季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_HEA_Q
(
    REALLTRANSHEAQID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC      VARGRAPHIC(100),
    SCORELEVEL        VARGRAPHIC(50),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSHEAQID)
);


-- 整体变压器运行健康状况得分-年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_HEA_Y
(
    REALLTRANSHEAYID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC      VARGRAPHIC(100),
    SCORELEVEL        VARGRAPHIC(50),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSHEAYID)
);



-- 整体变压器运行健康状况得分对比-季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_HEA_COM_Q
(
    REALLTRANSHEACOMQID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC     VARGRAPHIC(100),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    COMPARISON        VARGRAPHIC(50),
    RATIO             DECIMAL(8, 4),
    PRIMARY KEY (REALLTRANSHEACOMQID)
);


-- 整体变压器运行健康状况得分对比-年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_HEA_COM_Y
(
    REALLTRANSHEACOMYID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    PRODUCTMODELC     VARGRAPHIC(100),
    SCORE             INTEGER,
    CREATETIME        VARGRAPHIC(50),
    COMPARISON        VARGRAPHIC(50),
    RATIO             DECIMAL(8, 4),
    PRIMARY KEY (REALLTRANSHEACOMYID)
);
