-- 变压器供用电状况--季度
CREATE TABLE MAXIMO.RE_TRANS_PS_QUARTER
(
    RETRANSFORMERPSQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(31, 4),
    LOADRATIO                DECIMAL(31, 4),
    LOSSVALUE                DECIMAL(31, 4),
    LOSSRATIO                DECIMAL(31, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSQUARTERID)
);

-- 变压器供用电状况--年度
CREATE TABLE MAXIMO.RE_TRANS_PS_YEAR
(
    RETRANSFORMERPSYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100),
    ASSETYPE              VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    PRODUCTMODELB         VARGRAPHIC(100),
    PRODUCTMODELC         VARGRAPHIC(100),
    PARENT                VARGRAPHIC(100),
    LOADVALUE             DECIMAL(31, 4),
    LOADRATIO             DECIMAL(31, 4),
    LOSSVALUE             DECIMAL(31, 4),
    LOSSRATIO             DECIMAL(31, 4),
    CREATETIME            VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSYEARID)
);


-- 定时生成每月运行时长数据
CREATE TABLE MAXIMO.RE_TRANS_PS_RUN_MONTH
(
    RETRANSPSRUNMONTHID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME             VARGRAPHIC(100),
    ASSETYPE            VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    PRODUCTMODELB       VARGRAPHIC(100),
    PRODUCTMODELC       VARGRAPHIC(100),
    PARENT              VARGRAPHIC(100),
    RUNNINGTIME         DECIMAL(31, 4),
    DOWNTIME            DECIMAL(31, 4),
    RUNSTATUS           INT,
    COLTIME             TIMESTAMP,
    CREATETIME          TIMESTAMP,
    PARTICULARTIME      VARGRAPHIC(50),
    PRIMARY KEY (RETRANSPSRUNMONTHID)
);