-- 变压器供用电状况--季度
CREATE TABLE MAXIMO.RE_TRANS_PS_QUARTER
(
    RETRANSFORMERPSQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    LOSSDESC                 VARGRAPHIC(50),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSQUARTERID)
);

-- 变压器供用电状况--年度
CREATE TABLE MAXIMO.RE_TRANS_PS_YEAR
(
    RETRANSFORMERPSYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    LOSSDESC                 VARGRAPHIC(50),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSYEARID)
);


-- 变压器供用电状况--季度比对
CREATE TABLE MAXIMO.RE_TRANS_PS_COM_QUARTER
(
    RETRANSFORMERPSCOMQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSCOMQUARTERID)
);

-- 变压器供用电状况--年度比对
CREATE TABLE MAXIMO.RE_TRANS_PS_COM_YEAR
(
    RETRANSFORMERPSCOMYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSFORMERPSCOMYEARID)
);

-- 定时生成每月运行时长数据
CREATE TABLE MAXIMO.RE_TRANS_PS_RUN_MONTH
(
    RETRANSPSRUNMONTHID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME             VARGRAPHIC(100),
    ASSETYPE            VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    PRODUCTMODELB       VARGRAPHIC(100),
    PRODUCTMODELC       VARGRAPHIC(100),
    PARENT              VARGRAPHIC(100),
    RUNNINGTIME         DECIMAL(31, 4),
    DOWNTIME            DECIMAL(31, 4),
    RUNSTATUS           INT,
    COLTIME             TIMESTAMP,
    CREATETIME          TIMESTAMP,
    PARTICULARTIME      VARGRAPHIC(50),
    PRIMARY KEY (RETRANSPSRUNMONTHID)
);

