-- 整体变压器供用电状况--季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_QUARTER
(
    REALLTRANSPSQUARTERID    BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSQUARTERID)
);

-- 整体变压器供用电状况--年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_YEAR
(
    REALLTRANSPSYEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSYEARID)
);

-- 整体变压器供用电状况--季度比对
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_COM_QUARTER
(
    REALLTRANSPSCOMQUARTERID    BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSCOMQUARTERID)
);




-- 整体变压器供用电状况--年度比对
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_COM_YEAR
(
    REALLTRANSPSCOMYEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    LOADRATIO                DECIMAL(8, 4),
    LOSSVALUE                DECIMAL(8, 4),
    LOSSRATIO                DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSCOMYEARID)
);


-- 整体变压器供用电状况TOP3设备--季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_TOP3_QUARTER
(
    REALLTRANSPSTOP3QUARTERID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                        VARGRAPHIC(100),
    PRODUCTMODELC                   VARGRAPHIC(100),
    TOPIEDNAME1                     VARGRAPHIC(100),
    TOPIEDNAME2                     VARGRAPHIC(100),
    TOPIEDNAME3                     VARGRAPHIC(100),
    CREATETIME                      VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSTOP3QUARTERID)
);


-- 整体变压器供用电状况TOP3设备--年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_PS_TOP3_YEAR
(
    REALLTRANSPSTOP3YEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                        VARGRAPHIC(100),
    PRODUCTMODELC                   VARGRAPHIC(100),
    TOPIEDNAME1                     VARGRAPHIC(100),
    TOPIEDNAME2                     VARGRAPHIC(100),
    TOPIEDNAME3                     VARGRAPHIC(100),
    CREATETIME                      VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSPSTOP3YEARID)
);


