
-- 单台变压器报警分析-季度
CREATE TABLE MAXIMO.RE_TRANS_ALARM_QUARTER
(
    RETRANSALARMQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100 CODEUNITS16),
    ALARMLEVEL1COUNT      INTEGER,
    ALARMLEVEL1RATIO      DECIMAL(31, 4),
    ALARMLEVEL2COUNT      INTEGER,
    ALARMLEVEL2RATIO      DECIMAL(31, 4),
    ALARMLEVEL3COUNT      INTEGER,
    ALARMLEVEL3RATIO      DECIMAL(31, 4),
    VARIABLENAMEMAX       VARGRAPHIC(100 CODEUNITS16),
    CREATETIME            VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (RETRANSALARMQUARTERID)
);



-- 单台变压器报警分析-年度
CREATE TABLE MAXIMO.RE_TRANS_ALARM_YEAR
(
    RETRANSALARMYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100 CODEUNITS16),
    ALARMLEVEL1COUNT      INTEGER,
    ALARMLEVEL1RATIO      DECIMAL(31, 4),
    ALARMLEVEL2COUNT      INTEGER,
    ALARMLEVEL2RATIO      DECIMAL(31, 4),
    ALARMLEVEL3COUNT      INTEGER,
    ALARMLEVEL3RATIO      DECIMAL(31, 4),
    VARIABLENAMEMAX       VARGRAPHIC(100 CODEUNITS16),
    CREATETIME            VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (RETRANSALARMYEARID)
);