

-- 整体变压器报警分析-季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_ALARM_Q
(
    REALLTRANSALARMQID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                   VARGRAPHIC(100),
    PRODUCTMODEL               VARGRAPHIC(100),
    LOCATION                   VARGRAPHIC(100),
    ALARMLEVEL1COUNT           INTEGER,
    ALARMLEVEL1RATIO           DECIMAL(31, 4),
    ALARMLEVEL2COUNT           INTEGER,
    ALARMLEVEL2RATIO           DECIMAL(31, 4),
    ALARMLEVEL3COUNT           INTEGER,
    ALARMLEVEL3RATIO           DECIMAL(31, 4),
    VARIABLENAMEMAX            VARGRAPHIC(100 CODEUNITS16),
    CREATETIME                 VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLTRANSALARMQID)
);


-- 整体变压器报警分析-年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_ALARM_Y
(
    REALLTRANSALARMYID  BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    ALARMLEVEL1COUNT         INTEGER,
    ALARMLEVEL1RATIO         DECIMAL(31, 4),
    ALARMLEVEL2COUNT         INTEGER,
    ALARMLEVEL2RATIO         DECIMAL(31, 4),
    ALARMLEVEL3COUNT         INTEGER,
    ALARMLEVEL3RATIO         DECIMAL(31, 4),
    VARIABLENAMEMAX          VARGRAPHIC(100 CODEUNITS16),
    CREATETIME               VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLTRANSALARMYID)
);
