
-- 整体变压器运行时长-季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_FENG_Q
(
    REALLTRANSUEFENGQID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100 CODEUNITS16),
    LOCATION          VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL      VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODELB      VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODELC      VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME       DECIMAL(31, 4),
    CREATETIME        VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLTRANSUEFENGQID)
);

-- 整体变压器运行时长-年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_FENG_Y
(
    REALLTRANSUEFENGYID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100 CODEUNITS16),
    LOCATION          VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL      VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODELB      VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODELC      VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME       DECIMAL(31, 4),
    CREATETIME        VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLTRANSUEFENGYID)
);
