-- 单台变压器允运行停机时长及使用率--季度
CREATE TABLE MAXIMO.RE_TRANS_UE_QUARTER
(
    RETRANSUEQUARTERID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUEQUARTERID)
);

-- 单台变压器允运行停机时长及使用率--年度
CREATE TABLE MAXIMO.RE_TRANS_UE_YEAR
(
    RETRANSUEYEARID          BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUEYEARID)
);

-- 单台变压器允运行停机时长及使用率--季度比对
CREATE TABLE MAXIMO.RE_TRANS_UE_COM_QUARTER
(
    RETRANSUECOMQUARTERID    BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUECOMQUARTERID)
);


-- 单台变压器允运行停机时长及使用率--年度比对
CREATE TABLE MAXIMO.RE_TRANS_UE_COM_YEAR
(
    RETRANSUECOMYEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUECOMYEARID)
);



-- 单台变压器使用效率状况--月度最大负荷
CREATE TABLE MAXIMO.RE_TRANS_UE_MONTH
(
    RETRANSUEMONTHID         BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    LOADVALUE                DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUEMONTHID)
);

-- 单台变压器使用效率电流负荷状况--季度
CREATE TABLE MAXIMO.RE_TRANS_UE_INFO_QUARTER
(
    RETRANSUEINFOQUARTERID   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(8, 4),
    PHASECURRENTMIN          DECIMAL(8, 4),
    PHASECURRENTAVG          DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUEINFOQUARTERID)
);

-- 单台变压器使用效率电流负荷状况--年度
CREATE TABLE MAXIMO.RE_TRANS_UE_INFO_YEAR
(
    RETRANSUEINFOYEARID   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    PRODUCTMODELB            VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    PARENT                   VARGRAPHIC(100),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(8, 4),
    PHASECURRENTMIN          DECIMAL(8, 4),
    PHASECURRENTAVG          DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (RETRANSUEINFOYEARID)
);

