-- 整体变压器允运行停机时长及使用率--季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_QUARTER
(
    REALLTRANSUEQUARTERID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUEQUARTERID)
);


-- 整体变压器允运行停机时长及使用率--年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_YEAR
(
    REALLTRANSUEYEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUEYEARID)
);

-- 整体变压器允运行停机时长及使用率--季度比对
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_COM_QUARTER
(
    REALLTRANSUECOMQUARTERID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUECOMQUARTERID)
);

-- 整体变压器允运行停机时长及使用率--年度比对
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_COM_YEAR
(
    REALLTRANSUECOMYEARID       BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    RUNNINGTIME              DECIMAL(8, 4),
    UTILIZATIONRATIO         DECIMAL(8, 4),
    DOWNTIME                 DECIMAL(8, 4),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUECOMYEARID)
);


-- 整体变压器使用效率电流负荷状况--季度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_INFO_QUARTER
(
    REALLTRANSUEINFOQUARTERID   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(8, 4),
    PHASECURRENTMIN          DECIMAL(8, 4),
    PHASECURRENTAVG          DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUEINFOQUARTERID)
);

-- 整体变压器使用效率电流负荷状况--年度
CREATE TABLE MAXIMO.RE_ALL_TRANS_UE_INFO_YEAR
(
    REALLTRANSUEINFOYEARID   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(8, 4),
    PHASECURRENTMIN          DECIMAL(8, 4),
    PHASECURRENTAVG          DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(50),
    PRIMARY KEY (REALLTRANSUEINFOYEARID)
);