CREATE SEQUENCE YX_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YX_CURRENT
(
    YXID         BIGINT NOT NULL,
    IEDNAME      VARGRAPHIC(100 CODEUNITS16),
    COLTIME      TIMESTAMP,
    VARIABLENAME VARGRAPHIC(100 CODEUNITS16),
    VAL          INT,
    CREATETIME   TIMESTAMP
);



CREATE TABLE MAXIMO.YX_SCORE
(
    YXSCOREID    BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME      VARGRAPHIC(100 CODEUNITS16),
    COLTIME      TIMESTAMP,
    SCORE        int,
    HIGHLEVEL    int,
    VARIABLENAME VARGRAPHIC(100 CODEUNITS16),
    VAL          INT,
    CREATETIME   TIMESTAMP
);



