CREATE TABLE MAXIMO.YC_LOWPRESSURE_CURRENT
(
    YCLOWPRESSURECURRENTID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                VARGRAPHIC(100),
    COLTIME                TIMESTAMP,
    PHASEL1CURRENTPERCENT  DECIMAL(31, 2),
    PHASEL1L2VOLTAGE       DECIMAL(31, 2),
    PHASEL2CURRENTPERCENT  DECIMAL(31, 2),
    PHASEL2L3VOLTAGE       DECIMAL(31, 2),
    PHASEL3CURRENTPERCENT  DECIMAL(31, 2),
    PHASEL3L1VOLTAGE       DECIMAL(31, 2),
    ACTIVEELECTRICDEGREE   DECIMAL(31, 2),
    REACTIVEELECTRICDEGREE DECIMAL(31, 2),
    POWERFACTOR            DECIMAL(31, 2),
    OPERATIONNUMBER        INTEGER,
    CREATETIME             TIMESTAMP,
    PRIMARY KEY (YCLOWPRESSURECURRENTID)
);
