-- 月度评分
CREATE TABLE MAXIMO.RE_SCORE_MONTH
(
    REMEDIUMVOLTAGESCOREID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                VARGRAPHIC(100 CODEUNITS16),
    assetYpe               VARGRAPHIC(100 CODEUNITS16),
    productModel           VARGRAPHIC(100 CODEUNITS16),
    location               VARGRAPHIC(100 CODEUNITS16),
    fractionRatio          DECIMAL(31, 4),
    score                  INT,
    CREATETIME             VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (REMEDIUMVOLTAGESCOREID)
);


-- 季度评分
CREATE TABLE MAXIMO.RE_SCORE_QUARTER
(
    REMEDIUMVOLTAGESCOREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                       VARGRAPHIC(100 CODEUNITS16),
    assetYpe                      VARGRAPHIC(100 CODEUNITS16),
    productModel                  VARGRAPHIC(100 CODEUNITS16),
    location                      VARGRAPHIC(100 CODEUNITS16),
    fractionRatio                 DECIMAL(31, 4),
    score                         DECIMAL(8, 4),
    CREATETIME                    VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (REMEDIUMVOLTAGESCOREQUARTERID)
);


-- 年度评分
CREATE TABLE MAXIMO.RE_SCORE_YEAR
(
    REMEDIUMVOLTAGESCOREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                    VARGRAPHIC(100 CODEUNITS16),
    assetYpe                   VARGRAPHIC(100 CODEUNITS16),
    productModel                  VARGRAPHIC(100 CODEUNITS16),
    location                      VARGRAPHIC(100 CODEUNITS16),
    score                      DECIMAL(8, 4),
    CREATETIME                 VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (REMEDIUMVOLTAGESCOREYEARID)
);




-- 季度对比
CREATE TABLE MAXIMO.RE_COMPARE_QUARTER
(
    RECOMPAREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME            VARGRAPHIC(100 CODEUNITS16),
    assetYpe           VARGRAPHIC(100 CODEUNITS16),
    score              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100 CODEUNITS16),
    COMPARISON         VARGRAPHIC(50 CODEUNITS16),
    RATIO              DECIMAL(8, 4),
    PRIMARY KEY (RECOMPAREQUARTERID)
);



-- 年度对比
CREATE TABLE MAXIMO.RE_COMPARE_YEAR
(
    RECOMPAREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME            VARGRAPHIC(100 CODEUNITS16),
    assetYpe           VARGRAPHIC(100 CODEUNITS16),
    score              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100 CODEUNITS16),
    COMPARISON         VARGRAPHIC(50 CODEUNITS16),
    RATIO              DECIMAL(8, 4),
    PRIMARY KEY (RECOMPAREYEARID)
);




