-- 季度负荷率
CREATE TABLE MAXIMO.RE_LOAD_QUARTER
(
    RELOADQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME         VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR      DECIMAL(31, 4),
    CREATETIME      VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE        VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL    VARGRAPHIC(100 CODEUNITS16),
    LOCATION        VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RELOADQUARTERID)
);

-- 年度负荷率
CREATE TABLE MAXIMO.RE_LOAD_YEAR
(
    RELOADYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME      VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR   DECIMAL(31, 4),
    CREATETIME   VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE     VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL VARGRAPHIC(100 CODEUNITS16),
    LOCATION     VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RELOADYEARID)
);


-- 季度对比
CREATE TABLE MAXIMO.RE_LOAD_COMPARE_QUARTER
(
    RELOADCOMPAREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR             DECIMAL(31, 4),
    CREATETIME             VARGRAPHIC(100 CODEUNITS16),
    COMPARISON             VARGRAPHIC(50 CODEUNITS16),
    RATIO                  DECIMAL(31, 4),
    PRIMARY KEY (RELOADCOMPAREQUARTERID)
);


-- 年度对比
CREATE TABLE MAXIMO.RE_LOAD_COMPARE_YEAR
(
    RELOADCOMPAREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME             VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR          DECIMAL(31, 4),
    CREATETIME          VARGRAPHIC(100 CODEUNITS16),
    COMPARISON          VARGRAPHIC(50 CODEUNITS16),
    RATIO               DECIMAL(31, 4),
    PRIMARY KEY (RELOADCOMPAREYEARID)
);
