-- 总体季度负荷率评分
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_QUARTER
(
    RETOTALLOADQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE             VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL         VARGRAPHIC(100 CODEUNITS16),
    LOCATION             VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR           DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALLOADQUARTERID)
);


-- 总体年度负荷率评分
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_YEAR
(
    RETOTALLOADYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE          VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL      VARGRAPHIC(100 CODEUNITS16),
    LOCATION          VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR        DECIMAL(8, 4),
    CREATETIME        VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALLOADYEARID)
);


-- 总体季度负荷率对比
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_COMP_QUARTER
(
    RETOTALLOADCOMPAREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                    VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL                VARGRAPHIC(100 CODEUNITS16),
    LOCATION                    VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR                  DECIMAL(8, 4),
    CREATETIME                  VARGRAPHIC(100 CODEUNITS16),
    COMPARISON                  VARGRAPHIC(50 CODEUNITS16),
    RATIO                       DECIMAL(8, 4),
    PRIMARY KEY (RETOTALLOADCOMPAREQUARTERID)
);


-- 总体季度负荷率对比
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_COMP_YEAR
(
    RETOTALLOADCOMPAREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL             VARGRAPHIC(100 CODEUNITS16),
    LOCATION                 VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR               DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(100 CODEUNITS16),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    PRIMARY KEY (RETOTALLOADCOMPAREYEARID)
);

-- 总体季度负荷率等级
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_HEALTH_QUARTER
(
    RETOTALLOADHEALTHQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                   VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL               VARGRAPHIC(100 CODEUNITS16),
    LOCATION                   VARGRAPHIC(100 CODEUNITS16),
    EXCELLENT                  INT,
    GOOD                       INT,
    RANGE                      INT,
    CREATETIME                 VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALLOADHEALTHQUARTERID)
);


-- 总体年度负荷率等级
CREATE TABLE MAXIMO.RE_TOTAL_LOAD_HEALTH_YEAR
(
    RETOTALLOADHEALTHYEAR BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE              VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL          VARGRAPHIC(100 CODEUNITS16),
    LOCATION              VARGRAPHIC(100 CODEUNITS16),
    EXCELLENT             INT,
    GOOD                  INT,
    RANGE                 INT,
    CREATETIME            VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALLOADHEALTHYEAR)
);