-- 单台开关柜季度使用效率、运行时长
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_QUARTER
(
    REVOLTAGEUEQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME              VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE             VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL         VARGRAPHIC(100 CODEUNITS16),
    LOCATION             VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME          DECIMAL(31, 4),
    UTILIZATIONRATIO     DECIMAL(31, 4),
    CREATETIME           VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEUEQUARTERID)
);


-- 单台开关柜季度使用效率、运行时长
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_YEAR
(
    REVOLTAGEUEYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE          VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL      VARGRAPHIC(100 CODEUNITS16),
    LOCATION          VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME       DECIMAL(31, 4),
    UTILIZATIONRATIO  DECIMAL(31, 4),
    CREATETIME        VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEUEYEARID)
);


-- 单台中压开关柜季度使用效率、运行时长比对
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_COMP_QUARTER
(
    REVOLTAGEUECOMPQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE                 VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL             VARGRAPHIC(100 CODEUNITS16),
    LOCATION                 VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME              DECIMAL(31, 4),
    UTILIZATIONRATIO         DECIMAL(31, 4),
    CREATETIME               VARGRAPHIC(50 CODEUNITS16),
    COMPARISON               VARGRAPHIC(50 CODEUNITS16),
    RATIO                    DECIMAL(8, 4),
    PRIMARY KEY (REVOLTAGEUECOMPQUARTERID)
);

-- 单台开关柜年度使用效率、运行时长比对
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_COMP_YEAR
(
    REVOLTAGEUEYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME           VARGRAPHIC(100 CODEUNITS16),
    ASSETYPE          VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL      VARGRAPHIC(100 CODEUNITS16),
    LOCATION          VARGRAPHIC(100 CODEUNITS16),
    RUNNINGTIME       DECIMAL(31, 4),
    UTILIZATIONRATIO  DECIMAL(31, 4),
    CREATETIME        VARGRAPHIC(50 CODEUNITS16),
    COMPARISON        VARGRAPHIC(50 CODEUNITS16),
    RATIO             DECIMAL(8, 4),
    PRIMARY KEY (REVOLTAGEUEYEARID)
);


-- 单台开关柜季度统计信息
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_INFO_QUARTER
(
    REVOLTAGEUEINFOQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(31, 4),
    PHASECURRENTMIN          DECIMAL(31, 4),
    PHASECURRENTAVG          VARGRAPHIC(50 CODEUNITS16),
    CREATETIME               VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEUEINFOQUARTERID)
);

-- 单台开关柜年度统计信息
CREATE TABLE MAXIMO.RE_VOLTAGE_UE_INFO_YEAR
(
    REVOLTAGEUEINFOYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100 CODEUNITS16),
    MINMONTH              VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH              VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX       DECIMAL(31, 4),
    PHASECURRENTMIN       DECIMAL(31, 4),
    PHASECURRENTAVG       VARGRAPHIC(50 CODEUNITS16),
    CREATETIME            VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEUEINFOYEARID)
);



-- 单台中压开关柜季度报警分析
CREATE TABLE MAXIMO.RE_VOLTAGE_ALARM_QUARTER
(
    REVOLTAGEALARMQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100 CODEUNITS16),
    ALARMLEVEL1COUNT      INTEGER,
    ALARMLEVEL1RATIO      DECIMAL(31, 4),
    ALARMLEVEL2COUNT      INTEGER,
    ALARMLEVEL2RATIO      DECIMAL(31, 4),
    ALARMLEVEL3COUNT      INTEGER,
    ALARMLEVEL3RATIO      DECIMAL(31, 4),
    VARIABLENAMEMAX        VARGRAPHIC(100 CODEUNITS16),
    CREATETIME            VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEALARMQUARTERID)
);

-- 单台中压开关柜年度报警分析
CREATE TABLE MAXIMO.RE_VOLTAGE_ALARM_YEAR
(
    REVOLTAGEALARMYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME               VARGRAPHIC(100 CODEUNITS16),
    ALARMLEVEL1COUNT      INTEGER,
    ALARMLEVEL1RATIO      DECIMAL(31, 4),
    ALARMLEVEL2COUNT      INTEGER,
    ALARMLEVEL2RATIO      DECIMAL(31, 4),
    ALARMLEVEL3COUNT      INTEGER,
    ALARMLEVEL3RATIO      DECIMAL(31, 4),
    VARIABLENAMEMAX       VARGRAPHIC(100 CODEUNITS16),
    CREATETIME            VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REVOLTAGEALARMYEARID)
);
