-- 整体开关柜季度使用效率、运行时长
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_QUARTER
(
    REALLVOLTAGEUEQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL            VARGRAPHIC(100 CODEUNITS16),
    LOCATION                VARGRAPHIC(100 CODEUNITS16),
    TOTALRUNNINGTIME        DECIMAL(31, 4),
    AVGUTILIZATIONRATIO     DECIMAL(31, 4),
    CREATETIME              VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEUEQUARTERID)
);

-- 整体开关柜季度使用效率、运行时长比对
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_COMP_QUARTER
(
    REALLVOLTAGEUECOMPQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                    VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL                VARGRAPHIC(100 CODEUNITS16),
    LOCATION                    VARGRAPHIC(100 CODEUNITS16),
    TOTALRUNNINGTIME            DECIMAL(31, 4),
    AVGUTILIZATIONRATIO         DECIMAL(31, 4),
    CREATETIME                  VARGRAPHIC(50 CODEUNITS16),
    COMPARISON                  VARGRAPHIC(50 CODEUNITS16),
    RATIO                       DECIMAL(8, 4),
    PRIMARY KEY (REALLVOLTAGEUECOMPQUARTERID)
);


-- 整体开关柜年度使用效率、运行时长
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_YEAR
(
    REALLVOLTAGEUEQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL            VARGRAPHIC(100 CODEUNITS16),
    LOCATION                VARGRAPHIC(100 CODEUNITS16),
    TOTALRUNNINGTIME        DECIMAL(31, 4),
    AVGUTILIZATIONRATIO     DECIMAL(31, 4),
    CREATETIME              VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEUEQUARTERID)
);

-- 整体开关柜年度使用效率、运行时长比对
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_COMP_YEAR
(
    REALLVOLTAGEUECOMPQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                    VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL                VARGRAPHIC(100 CODEUNITS16),
    LOCATION                    VARGRAPHIC(100 CODEUNITS16),
    TOTALRUNNINGTIME            DECIMAL(31, 4),
    AVGUTILIZATIONRATIO         DECIMAL(31, 4),
    CREATETIME                  VARGRAPHIC(50 CODEUNITS16),
    COMPARISON                  VARGRAPHIC(50 CODEUNITS16),
    RATIO                       DECIMAL(8, 4),
    PRIMARY KEY (REALLVOLTAGEUECOMPQUARTERID)
);

-- 整体中压开关使用效率评分-季度
create table RE_ALL_VOL_UE_HEALTH_QUARTER
(
    REALLVOLTAGEUEHEALTHQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                      VARGRAPHIC(100),
    PRODUCTMODEL                  VARGRAPHIC(100),
    LOCATION                      VARGRAPHIC(100),
    EXCELLENT                     INTEGER,
    GOOD                          INTEGER,
    RANGE                         INTEGER,
    CREATETIME                    VARGRAPHIC(50),
    PRIMARY KEY (REALLVOLTAGEUEHEALTHQUARTERID)
);

-- 整体开关柜季度统计信息
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_INFO_QUARTER
(
    REALLVOLTAGEUEINFOQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                    VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL                VARGRAPHIC(100 CODEUNITS16),
    LOCATION                    VARGRAPHIC(100 CODEUNITS16),
    MINMONTH                    VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                    VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX             DECIMAL(31, 4),
    PHASECURRENTMIN             DECIMAL(31, 4),
    PHASECURRENTAVG             VARGRAPHIC(50 CODEUNITS16),
    CREATETIME                  VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEUEINFOQUARTERID)
);

-- 整体开关柜年度统计信息
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_UE_INFO_YEAR
(
    REALLVOLTAGEUEINFOYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL             VARGRAPHIC(100 CODEUNITS16),
    LOCATION                 VARGRAPHIC(100 CODEUNITS16),
    MINMONTH                 VARGRAPHIC(50 CODEUNITS16),
    MAXMONTH                 VARGRAPHIC(50 CODEUNITS16),
    PHASECURRENTMAX          DECIMAL(31, 4),
    PHASECURRENTMIN          DECIMAL(31, 4),
    PHASECURRENTAVG          VARGRAPHIC(50 CODEUNITS16),
    CREATETIME               VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEUEINFOYEARID)
);


-- 整体中压开关使用效率评分-年度
create table RE_ALL_VOL_UE_HEALTH_YEAR
(
    REALLVOLTAGEUEHEALTHQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                      VARGRAPHIC(100),
    PRODUCTMODEL                  VARGRAPHIC(100),
    LOCATION                      VARGRAPHIC(100),
    EXCELLENT                     INTEGER,
    GOOD                          INTEGER,
    RANGE                         INTEGER,
    CREATETIME                    VARGRAPHIC(50),
    PRIMARY KEY (REALLVOLTAGEUEHEALTHQUARTERID)
);



-- 整体开关柜季度报警统计信息
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_ALARM_QUARTER
(
    REALLVOLTAGEALARMQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                   VARGRAPHIC(100),
    PRODUCTMODEL               VARGRAPHIC(100),
    LOCATION                   VARGRAPHIC(100),
    ALARMLEVEL1COUNT           INTEGER,
    ALARMLEVEL1RATIO           DECIMAL(31, 4),
    ALARMLEVEL2COUNT           INTEGER,
    ALARMLEVEL2RATIO           DECIMAL(31, 4),
    ALARMLEVEL3COUNT           INTEGER,
    ALARMLEVEL3RATIO           DECIMAL(31, 4),
    VARIABLENAMEMAX            VARGRAPHIC(100 CODEUNITS16),
    CREATETIME                 VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEALARMQUARTERID)
);

-- 整体开关柜年度报警统计信息
CREATE TABLE MAXIMO.RE_ALL_VOLTAGE_ALARM_YEAR
(
    REALLVOLTAGEALARMYEARID  BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    ALARMLEVEL1COUNT         INTEGER,
    ALARMLEVEL1RATIO         DECIMAL(31, 4),
    ALARMLEVEL2COUNT         INTEGER,
    ALARMLEVEL2RATIO         DECIMAL(31, 4),
    ALARMLEVEL3COUNT         INTEGER,
    ALARMLEVEL3RATIO         DECIMAL(31, 4),
    VARIABLENAMEMAX          VARGRAPHIC(100 CODEUNITS16),
    CREATETIME               VARGRAPHIC(50 CODEUNITS16),
    PRIMARY KEY (REALLVOLTAGEALARMYEARID)
);




-- 整体中压设备速断和过流、延时过流、差动保护最多的设备-季度
create table RE_ALL_VOL_UE_FAIL_QUARTER
(
    REALLVOLUEFAILQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    QUICKBREAKDEVICE        VARGRAPHIC(100 CODEUNITS16),
    OVERCURRENTDEVICE       VARGRAPHIC(100 CODEUNITS16),
    OVERCURRENTDELAYDEVICE  VARGRAPHIC(100 CODEUNITS16),
    CREATETIME              VARGRAPHIC(50),
    PRIMARY KEY (REALLVOLUEFAILQUARTERID)
);



-- 整体中压设备速断和过流、延时过流、差动保护最多的设备-年度
create table RE_ALL_VOL_UE_FAIL_YEAR
(
    REALLVOLUEFAILYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    QUICKBREAKDEVICE        VARGRAPHIC(100 CODEUNITS16),
    OVERCURRENTDEVICE       VARGRAPHIC(100 CODEUNITS16),
    OVERCURRENTDELAYDEVICE  VARGRAPHIC(100 CODEUNITS16),
    CREATETIME              VARGRAPHIC(50),
    PRIMARY KEY (REALLVOLUEFAILYEARID)
);