-- 总体月度评分
CREATE TABLE MAXIMO.RE_TOTAL_SCORE_MONTH
(
    RETOTALSCOREMONTHID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE            VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL        VARGRAPHIC(100 CODEUNITS16),
    LOCATION            VARGRAPHIC(100 CODEUNITS16),
    SCORE               DECIMAL(8, 4),
    CREATETIME          VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALSCOREMONTHID)
);


-- 总体季度评分
CREATE TABLE MAXIMO.RE_TOTAL_SCORE_QUARTER
(
    RETOTALSCOREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE              VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL          VARGRAPHIC(100 CODEUNITS16),
    LOCATION              VARGRAPHIC(100 CODEUNITS16),
    SCORE                 DECIMAL(8, 4),
    CREATETIME            VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALSCOREQUARTERID)
);


-- 总体年度评分
CREATE TABLE MAXIMO.RE_TOTAL_SCORE_YEAR
(
    RETOTALSCOREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE           VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL       VARGRAPHIC(100 CODEUNITS16),
    LOCATION           VARGRAPHIC(100 CODEUNITS16),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RETOTALSCOREYEARID)
);


-- 总体季度对比
CREATE TABLE MAXIMO.RE_TOTAL_COMPARE_QUARTER
(
    RETOTALCOMPAREQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE                VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL            VARGRAPHIC(100 CODEUNITS16),
    LOCATION                VARGRAPHIC(100 CODEUNITS16),
    SCORE                   DECIMAL(8, 4),
    CREATETIME              VARGRAPHIC(100 CODEUNITS16),
    COMPARISON              VARGRAPHIC(50 CODEUNITS16),
    RATIO                   DECIMAL(8, 4),
    PRIMARY KEY (RETOTALCOMPAREQUARTERID)
);


-- 总体年度对比
CREATE TABLE MAXIMO.RE_TOTAL_COMPARE_YEAR
(
    RETOTALCOMPAREYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    ASSETYPE             VARGRAPHIC(100 CODEUNITS16),
    PRODUCTMODEL         VARGRAPHIC(100 CODEUNITS16),
    LOCATION             VARGRAPHIC(100 CODEUNITS16),
    SCORE                DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100 CODEUNITS16),
    COMPARISON           VARGRAPHIC(50 CODEUNITS16),
    RATIO                DECIMAL(8, 4),
    PRIMARY KEY (RETOTALCOMPAREYEARID)
);

