-- 月度负荷率
CREATE TABLE MAXIMO.RE_LOAD_MONTH
(
    RELOADMONTHID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME       VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR    DECIMAL(31, 4),
    CREATETIME    VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RELOADMONTHID)
);

-- 季度负荷率
CREATE TABLE MAXIMO.RE_LOAD_QUARTER
(
    RELOADQUARTERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME         VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR      DECIMAL(31, 4),
    CREATETIME      VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RELOADQUARTERID)
);

-- 年度负荷率
CREATE TABLE MAXIMO.RE_LOAD_YEAR
(
    RELOADYEARID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ),
    IEDNAME      VARGRAPHIC(100 CODEUNITS16),
    LOADFACTOR   DECIMAL(31, 4),
    CREATETIME   VARGRAPHIC(100 CODEUNITS16),
    PRIMARY KEY (RELOADYEARID)
);

