-- 遥测
CREATE SEQUENCE YC_MEDIUM_VOLTAGE_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YC_MEDIUM_VOLTAGE_CURRENT
(
    YCMEDIUMVOLTAGEID      BIGINT NOT NULL,
    IEDNAME                VARGRAPHIC(100 CODEUNITS16),
    COLTIME                TIMESTAMP,
    CIRCUITBREAKER         INTEGER,
    POSITIVEREACTIVE       INTEGER,
    POSITIVEACTIVE         INTEGER,
    EARTHKNIFE             INTEGER,
    REVERSEREACTIVE        INTEGER,
    REVERSEACTIVE          INTEGER,
    HANDCARTPOSITION       INTEGER,
    AMBIENTTEMPERATURE     INTEGER,
    CCABLETEMPERATURE      INTEGER,
    BCABLETEMPERATURE      INTEGER,
    ACABLETEMPERATURE      INTEGER,
    CLOWERARMTEMPERATURE   INTEGER,
    BLOWERARMTEMPERATURE   INTEGER,
    ALOWERARMTEMPERATURE   INTEGER,
    CUPPERARMTEMPERATURE   INTEGER,
    BUPPERARMTEMPERATURE   INTEGER,
    AUPPERARMTEMPERATURE   INTEGER,
    APHASECURRENT          INTEGER,
    BPHASECURRENT          INTEGER,
    CPHASECURRENT          INTEGER,
    ABLINEVOLTAGE          INTEGER,
    BCLINEVOLTAGE          INTEGER,
    CALINEVOLTAGE          INTEGER,
    ZEROSEQUENCECURRENT    INTEGER,
    FREQUENCY              INTEGER,
    ACTIVEPOWER            INTEGER,
    REACTIVEPOWER          INTEGER,
    APPARENTPOWER          INTEGER,
    ACTIVEELECTRICDEGREE   INTEGER,
    REACTIVEELECTRICDEGREE INTEGER,
    CREATETIME             TIMESTAMP
);

CREATE SEQUENCE YC_MEDIUM_VOLTAGE_LOG_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YC_MEDIUM_VOLTAGE_LOG
(
    YCMEDIUMVOLTAGELOGID   BIGINT NOT NULL,
    IEDNAME                VARGRAPHIC(100 CODEUNITS16),
    COLTIME                TIMESTAMP,
    CIRCUITBREAKER         INTEGER,
    POSITIVEREACTIVE       INTEGER,
    POSITIVEACTIVE         INTEGER,
    EARTHKNIFE             INTEGER,
    REVERSEREACTIVE        INTEGER,
    REVERSEACTIVE          INTEGER,
    HANDCARTPOSITION       INTEGER,
    AMBIENTTEMPERATURE     INTEGER,
    CCABLETEMPERATURE      INTEGER,
    BCABLETEMPERATURE      INTEGER,
    ACABLETEMPERATURE      INTEGER,
    CLOWERARMTEMPERATURE   INTEGER,
    BLOWERARMTEMPERATURE   INTEGER,
    ALOWERARMTEMPERATURE   INTEGER,
    CUPPERARMTEMPERATURE   INTEGER,
    BUPPERARMTEMPERATURE   INTEGER,
    AUPPERARMTEMPERATURE   INTEGER,
    APHASECURRENT          INTEGER,
    BPHASECURRENT          INTEGER,
    CPHASECURRENT          INTEGER,
    ABLINEVOLTAGE          INTEGER,
    BCLINEVOLTAGE          INTEGER,
    CALINEVOLTAGE          INTEGER,
    ZEROSEQUENCECURRENT    INTEGER,
    FREQUENCY              INTEGER,
    ACTIVEPOWER            INTEGER,
    REACTIVEPOWER          INTEGER,
    APPARENTPOWER          INTEGER,
    ACTIVEELECTRICDEGREE   INTEGER,
    REACTIVEELECTRICDEGREE INTEGER,
    CREATETIME             TIMESTAMP
);


-- 遥信
CREATE SEQUENCE YX_MEDIUM_VOLTAGE_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;


CREATE TABLE MAXIMO.YX_MEDIUM_VOLTAGE_CURRENT
(
    YCMEDIUMVOLTAGEID        BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    QUICKBREAK               INTEGER,
    OVERCURRENT              INTEGER,
    OVERCURRENTDELAY         INTEGER,
    NOENERGYDTORAGE          INTEGER,
    CIRCUITDISCONNECTION     INTEGER,
    CCABLEOVERTEMPERATURE    INTEGER,
    BCABLEOVERTEMPERATURE    INTEGER,
    ACABLEOVERTEMPERATURE    INTEGER,
    CLOWERARMOVERTEMPERATURE INTEGER,
    BLOWERARMOVERTEMPERATURE INTEGER,
    ALOWERARMOVERTEMPERATURE INTEGER,
    CUPPERARMOVERTEMPERATURE INTEGER,
    BUPPERARMOVERTEMPERATURE INTEGER,
    AUPPERARMOVERTEMPERATURE INTEGER,
    CREATETIME               TIMESTAMP
);



CREATE SEQUENCE YX_MEDIUM_VOLTAGE_LOG_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;

CREATE TABLE MAXIMO.YX_MEDIUM_VOLTAGE_LOG
(
    YCMEDIUMVOLTAGELOGID        BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    QUICKBREAK               INTEGER,
    OVERCURRENT              INTEGER,
    OVERCURRENTDELAY         INTEGER,
    NOENERGYDTORAGE          INTEGER,
    CIRCUITDISCONNECTION     INTEGER,
    CCABLEOVERTEMPERATURE    INTEGER,
    BCABLEOVERTEMPERATURE    INTEGER,
    ACABLEOVERTEMPERATURE    INTEGER,
    CLOWERARMOVERTEMPERATURE INTEGER,
    BLOWERARMOVERTEMPERATURE INTEGER,
    ALOWERARMOVERTEMPERATURE INTEGER,
    CUPPERARMOVERTEMPERATURE INTEGER,
    BUPPERARMOVERTEMPERATURE INTEGER,
    AUPPERARMOVERTEMPERATURE INTEGER,
    CREATETIME               TIMESTAMP
);