-- 遥测
CREATE SEQUENCE YC_MEDIUM_VOLTAGE_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YC_MEDIUM_VOLTAGE_CURRENT
(
    YCMEDIUMVOLTAGEID        BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    CIRCUITBREAKER           DECIMAL(31, 2),
    POSITIVEREACTIVE         DECIMAL(31, 2),
    POSITIVEACTIVE           DECIMAL(31, 2),
    EARTHKNIFE               DECIMAL(31, 2),
    REVERSEREACTIVE          DECIMAL(31, 2),
    REVERSEACTIVE            DECIMAL(31, 2),
    HANDCARTPOSITION         DECIMAL(31, 2),
    AMBIENTTEMPERATURE       DECIMAL(31, 2),
    CCABLETEMPERATURE        DECIMAL(31, 2),
    BCABLETEMPERATURE        DECIMAL(31, 2),
    ACABLETEMPERATURE        DECIMAL(31, 2),
    CLOWERARMTEMPERATURE     DECIMAL(31, 2),
    BLOWERARMTEMPERATURE     DECIMAL(31, 2),
    ALOWERARMTEMPERATURE     DECIMAL(31, 2),
    CUPPERARMTEMPERATURE     DECIMAL(31, 2),
    BUPPERARMTEMPERATURE     DECIMAL(31, 2),
    AUPPERARMTEMPERATURE     DECIMAL(31, 2),
    APHASECURRENT            DECIMAL(31, 2),
    BPHASECURRENT            DECIMAL(31, 2),
    CPHASECURRENT            DECIMAL(31, 2),
    ABLINEVOLTAGE            DECIMAL(31, 2),
    BCLINEVOLTAGE            DECIMAL(31, 2),
    CALINEVOLTAGE            DECIMAL(31, 2),
    ZEROSEQUENCECURRENT      DECIMAL(31, 2),
    FREQUENCY                DECIMAL(31, 2),
    ACTIVEPOWER              DECIMAL(31, 2),
    REACTIVEPOWER            DECIMAL(31, 2),
    APPARENTPOWER            DECIMAL(31, 2),
    ACTIVEELECTRICDEGREE     DECIMAL(31, 2),
    REACTIVEELECTRICDEGREE   DECIMAL(31, 2),
    LINEVOLTAGE              DECIMAL(31, 2),
    LINECURRENT              DECIMAL(31, 2),
    CAPACITANCEREACTIVEPOWER DECIMAL(31, 2),
    REACTIVEPOWERSYMBOL      DECIMAL(31, 2),
    CAPACITANCEACTIVEPOWER   DECIMAL(31, 2),
    NO1OPENINGVOLTAGE        DECIMAL(31, 2),
    NO1BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO1CCAPACITANCECURRENT   DECIMAL(31, 2),
    NO2OPENINGVOLTAGE        DECIMAL(31, 2),
    NO2BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO2CCAPACITANCECURRENT   DECIMAL(31, 2),
    NO3OPENINGVOLTAGE        DECIMAL(31, 2),
    NO3BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO3CCAPACITANCECURR      DECIMAL(31, 2),
    CREATETIME               TIMESTAMP
);

CREATE SEQUENCE YC_MEDIUM_VOLTAGE_LOG_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YC_MEDIUM_VOLTAGE_LOG
(
    YCMEDIUMVOLTAGELOGID     BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    CIRCUITBREAKER           DECIMAL(31, 2),
    POSITIVEREACTIVE         DECIMAL(31, 2),
    POSITIVEACTIVE           DECIMAL(31, 2),
    EARTHKNIFE               DECIMAL(31, 2),
    REVERSEREACTIVE          DECIMAL(31, 2),
    REVERSEACTIVE            DECIMAL(31, 2),
    HANDCARTPOSITION         DECIMAL(31, 2),
    AMBIENTTEMPERATURE       DECIMAL(31, 2),
    CCABLETEMPERATURE        DECIMAL(31, 2),
    BCABLETEMPERATURE        DECIMAL(31, 2),
    ACABLETEMPERATURE        DECIMAL(31, 2),
    CLOWERARMTEMPERATURE     DECIMAL(31, 2),
    BLOWERARMTEMPERATURE     DECIMAL(31, 2),
    ALOWERARMTEMPERATURE     DECIMAL(31, 2),
    CUPPERARMTEMPERATURE     DECIMAL(31, 2),
    BUPPERARMTEMPERATURE     DECIMAL(31, 2),
    AUPPERARMTEMPERATURE     DECIMAL(31, 2),
    APHASECURRENT            DECIMAL(31, 2),
    BPHASECURRENT            DECIMAL(31, 2),
    CPHASECURRENT            DECIMAL(31, 2),
    ABLINEVOLTAGE            DECIMAL(31, 2),
    BCLINEVOLTAGE            DECIMAL(31, 2),
    CALINEVOLTAGE            DECIMAL(31, 2),
    ZEROSEQUENCECURRENT      DECIMAL(31, 2),
    FREQUENCY                DECIMAL(31, 2),
    ACTIVEPOWER              DECIMAL(31, 2),
    REACTIVEPOWER            DECIMAL(31, 2),
    APPARENTPOWER            DECIMAL(31, 2),
    ACTIVEELECTRICDEGREE     DECIMAL(31, 2),
    REACTIVEELECTRICDEGREE   DECIMAL(31, 2),
    LINEVOLTAGE              DECIMAL(31, 2),
    LINECURRENT              DECIMAL(31, 2),
    CAPACITANCEREACTIVEPOWER DECIMAL(31, 2),
    REACTIVEPOWERSYMBOL      DECIMAL(31, 2),
    CAPACITANCEACTIVEPOWER   DECIMAL(31, 2),
    NO1OPENINGVOLTAGE        DECIMAL(31, 2),
    NO1BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO1CCAPACITANCECURRENT   DECIMAL(31, 2),
    NO2OPENINGVOLTAGE        DECIMAL(31, 2),
    NO2BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO2CCAPACITANCECURRENT   DECIMAL(31, 2),
    NO3OPENINGVOLTAGE        DECIMAL(31, 2),
    NO3BCAPACITANCECURRENT   DECIMAL(31, 2),
    NO3CCAPACITANCECURRENT   DECIMAL(31, 2),
    CREATETIME               TIMESTAMP
);


-- 遥信
CREATE SEQUENCE YX_MEDIUM_VOLTAGE_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;


CREATE TABLE MAXIMO.YX_MEDIUM_VOLTAGE_CURRENT
(
    YCMEDIUMVOLTAGEID        BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    QUICKBREAK               INTEGER,
    OVERCURRENT              INTEGER,
    OVERCURRENTDELAY         INTEGER,
    NOENERGYDTORAGE          INTEGER,
    CIRCUITDISCONNECTION     INTEGER,
    CCABLEOVERTEMPERATURE    INTEGER,
    BCABLEOVERTEMPERATURE    INTEGER,
    ACABLEOVERTEMPERATURE    INTEGER,
    CLOWERARMOVERTEMPERATURE INTEGER,
    BLOWERARMOVERTEMPERATURE INTEGER,
    ALOWERARMOVERTEMPERATURE INTEGER,
    CUPPERARMOVERTEMPERATURE INTEGER,
    BUPPERARMOVERTEMPERATURE INTEGER,
    AUPPERARMOVERTEMPERATURE INTEGER,
    CREATETIME               TIMESTAMP
);



CREATE SEQUENCE YX_MEDIUM_VOLTAGE_LOG_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;

CREATE TABLE MAXIMO.YX_MEDIUM_VOLTAGE_LOG
(
    YCMEDIUMVOLTAGELOGID     BIGINT NOT NULL,
    IEDNAME                  VARGRAPHIC(100 CODEUNITS16),
    COLTIME                  TIMESTAMP,
    QUICKBREAK               INTEGER,
    OVERCURRENT              INTEGER,
    OVERCURRENTDELAY         INTEGER,
    NOENERGYDTORAGE          INTEGER,
    CIRCUITDISCONNECTION     INTEGER,
    CCABLEOVERTEMPERATURE    INTEGER,
    BCABLEOVERTEMPERATURE    INTEGER,
    ACABLEOVERTEMPERATURE    INTEGER,
    CLOWERARMOVERTEMPERATURE INTEGER,
    BLOWERARMOVERTEMPERATURE INTEGER,
    ALOWERARMOVERTEMPERATURE INTEGER,
    CUPPERARMOVERTEMPERATURE INTEGER,
    BUPPERARMOVERTEMPERATURE INTEGER,
    AUPPERARMOVERTEMPERATURE INTEGER,
    CREATETIME               TIMESTAMP
);