CREATE SEQUENCE YC_TRANSFORMER_CURRENT_SEQ AS BIGINT
    START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1000 CYCLE ORDER;



CREATE TABLE MAXIMO.YC_TRANSFORMER_CURRENT
(
    YCTRANSFORMERID    BIGINT NOT NULL,
    IEDNAME           VARGRAPHIC(100 CODEUNITS16),
    COLTIME           TIMESTAMP,
    APhaseTemperature DECIMAL(31, 2),
    BPhaseTemperature DECIMAL(31, 2),
    CPhaseTemperature DECIMAL(31, 2),
    DRoadTemperature  DECIMAL(31, 2),
    CREATETIME        TIMESTAMP
);
