create table RE_SCORE_MONTH
(
    REMEDIUMVOLTAGESCOREID BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    FRACTIONRATIO          DECIMAL(31, 4),
    SCORE                  INTEGER,
    CREATETIME             VARGRAPHIC(100)
);

comment on table RE_SCORE_MONTH is '评分表';

comment on column RE_SCORE_MONTH.REMEDIUMVOLTAGESCOREID is '主键';

comment on column RE_SCORE_MONTH.IEDNAME is '设备编码';

comment on column RE_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_MONTH.LOCATION is '位置';

comment on column RE_SCORE_MONTH.FRACTIONRATIO is '评分系数';

comment on column RE_SCORE_MONTH.SCORE is '评分';

comment on column RE_SCORE_MONTH.CREATETIME is '时间月份';

INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50, '2020-02');
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (4, 'AH02', '中压开关设备', '35kV', 'A001', 0.0294, 60, '2020-02');
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (5, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 55, '2020-02');