create table RE_COMPARE_QUARTER
(
    RECOMPAREQUARTERID BIGINT
        primary key,
    IEDNAME            VARGRAPHIC(100),
    ASSETYPE           VARGRAPHIC(100),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100),
    COMPARISON         VARGRAPHIC(50),
    RATIO              DECIMAL(8, 4),
    ROWSTAMP           BIGINT not null
);

comment on table RE_COMPARE_QUARTER is '季度对比及变化率表';

comment on column RE_COMPARE_QUARTER.IEDNAME is '设备编码';

comment on column RE_COMPARE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_COMPARE_QUARTER.SCORE is '得分';

comment on column RE_COMPARE_QUARTER.CREATETIME is '时间';

comment on column RE_COMPARE_QUARTER.COMPARISON is '对比上季度';

comment on column RE_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, 'AH01', '中压开关设备', 50.0000, '2020-1', '有所提升', 0.1363, 3707049);
create table RE_COMPARE_YEAR
(
    RECOMPAREYEARID BIGINT
        primary key,
    IEDNAME         VARGRAPHIC(100),
    ASSETYPE        VARGRAPHIC(100),
    SCORE           DECIMAL(8, 4),
    CREATETIME      VARGRAPHIC(100),
    COMPARISON      VARGRAPHIC(50),
    RATIO           DECIMAL(8, 4),
    ROWSTAMP        BIGINT not null
);

comment on table RE_COMPARE_YEAR is '年度对比及变化率表';

comment on column RE_COMPARE_YEAR.RECOMPAREYEARID is '主键';

comment on column RE_COMPARE_YEAR.IEDNAME is '设备编码';

comment on column RE_COMPARE_YEAR.ASSETYPE is '设备类别';

comment on column RE_COMPARE_YEAR.SCORE is '得分';

comment on column RE_COMPARE_YEAR.CREATETIME is '年份时间';

comment on column RE_COMPARE_YEAR.COMPARISON is '对比结果';

comment on column RE_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_COMPARE_YEAR (RECOMPAREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', 50.0000, '2020', '有所提升', 0.6666, 3707906);
create table RE_LOAD_COMPARE_QUARTER
(
    RELOADCOMPAREQUARTERID BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    LOADFACTOR             DECIMAL(31, 4),
    CREATETIME             VARGRAPHIC(100),
    COMPARISON             VARGRAPHIC(50),
    RATIO                  DECIMAL(31, 4)
);

comment on table RE_LOAD_COMPARE_QUARTER is '单台中压开关柜负荷率季度比对';

comment on column RE_LOAD_COMPARE_QUARTER.RELOADCOMPAREQUARTERID is '主键';

comment on column RE_LOAD_COMPARE_QUARTER.IEDNAME is '设备编码';

comment on column RE_LOAD_COMPARE_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_LOAD_COMPARE_QUARTER.CREATETIME is '时间-季度';

comment on column RE_LOAD_COMPARE_QUARTER.COMPARISON is '对比结果';

comment on column RE_LOAD_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_LOAD_COMPARE_QUARTER (RELOADCOMPAREQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO) VALUES (3, 'AH01', 0.0018, '2020-1', '有所下降', -0.4000);
INSERT INTO MAXIMO.RE_LOAD_COMPARE_QUARTER (RELOADCOMPAREQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO) VALUES (4, 'AH01', 0.0030, '2019-4', '', 0.0000);
create table RE_LOAD_COMPARE_YEAR
(
    RELOADCOMPAREYEARID BIGINT
        primary key,
    IEDNAME             VARGRAPHIC(100),
    LOADFACTOR          DECIMAL(31, 4),
    CREATETIME          VARGRAPHIC(100),
    COMPARISON          VARGRAPHIC(50),
    RATIO               DECIMAL(31, 4)
);

comment on table RE_LOAD_COMPARE_YEAR is '单台中压开关柜负荷率年度比对';

comment on column RE_LOAD_COMPARE_YEAR.RELOADCOMPAREYEARID is '主键';

comment on column RE_LOAD_COMPARE_YEAR.IEDNAME is '设备编码';

comment on column RE_LOAD_COMPARE_YEAR.LOADFACTOR is '负荷率';

comment on column RE_LOAD_COMPARE_YEAR.CREATETIME is '时间-年度';

comment on column RE_LOAD_COMPARE_YEAR.COMPARISON is '对比往年结果';

comment on column RE_LOAD_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_LOAD_COMPARE_YEAR (RELOADCOMPAREYEARID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO) VALUES (1, 'AH01', 0.0018, '2020', '有所下降', -0.1000);
create table RE_LOAD_QUARTER
(
    RELOADQUARTERID BIGINT
        primary key,
    IEDNAME         VARGRAPHIC(100),
    LOADFACTOR      DECIMAL(31, 4),
    CREATETIME      VARGRAPHIC(100)
);

comment on table RE_LOAD_QUARTER is '单台开关柜负荷率-季度';

comment on column RE_LOAD_QUARTER.RELOADQUARTERID is '主键';

comment on column RE_LOAD_QUARTER.IEDNAME is '设备编码';

comment on column RE_LOAD_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_LOAD_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_LOAD_QUARTER (RELOADQUARTERID, IEDNAME, LOADFACTOR, CREATETIME) VALUES (1, 'AH01', 0.0018, '2020-1');
INSERT INTO MAXIMO.RE_LOAD_QUARTER (RELOADQUARTERID, IEDNAME, LOADFACTOR, CREATETIME) VALUES (2, 'AH01', 0.0030, '2019-4');
create table RE_LOAD_YEAR
(
    RELOADYEARID BIGINT
        primary key,
    IEDNAME      VARGRAPHIC(100),
    LOADFACTOR   DECIMAL(31, 4),
    CREATETIME   VARGRAPHIC(100)
);

comment on table RE_LOAD_YEAR is '单台开关柜负荷率-年度';

comment on column RE_LOAD_YEAR.RELOADYEARID is '主键';

comment on column RE_LOAD_YEAR.IEDNAME is '设备编码';

comment on column RE_LOAD_YEAR.LOADFACTOR is '负荷率';

comment on column RE_LOAD_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_LOAD_YEAR (RELOADYEARID, IEDNAME, LOADFACTOR, CREATETIME) VALUES (2, 'AH01', 0.0018, '2020');
INSERT INTO MAXIMO.RE_LOAD_YEAR (RELOADYEARID, IEDNAME, LOADFACTOR, CREATETIME) VALUES (3, 'AH01', 0.0020, '2019');
create table RE_SCORE_MONTH
(
    REMEDIUMVOLTAGESCOREID BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    FRACTIONRATIO          DECIMAL(31, 4),
    SCORE                  INTEGER,
    CREATETIME             VARGRAPHIC(100)
);

comment on table RE_SCORE_MONTH is '评分表';

comment on column RE_SCORE_MONTH.REMEDIUMVOLTAGESCOREID is '主键';

comment on column RE_SCORE_MONTH.IEDNAME is '设备编码';

comment on column RE_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_MONTH.LOCATION is '位置';

comment on column RE_SCORE_MONTH.FRACTIONRATIO is '评分系数';

comment on column RE_SCORE_MONTH.SCORE is '评分';

comment on column RE_SCORE_MONTH.CREATETIME is '时间月份';

INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50, '2020-02');
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (4, 'AH02', '中压开关设备', '35kV', 'A001', 0.0294, 60, '2020-02');
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME) VALUES (5, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 55, '2020-02');
create table RE_SCORE_QUARTER
(
    REMEDIUMVOLTAGESCOREQUARTERID BIGINT
        primary key,
    IEDNAME                       VARGRAPHIC(100),
    ASSETYPE                      VARGRAPHIC(100),
    PRODUCTMODEL                  VARGRAPHIC(100),
    LOCATION                      VARGRAPHIC(100),
    FRACTIONRATIO                 DECIMAL(31, 4),
    SCORE                         DECIMAL(8, 4),
    CREATETIME                    VARGRAPHIC(100),
    ROWSTAMP                      BIGINT not null
);

comment on table RE_SCORE_QUARTER is '季度评分表';

comment on column RE_SCORE_QUARTER.IEDNAME is '设备编号';

comment on column RE_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_QUARTER.LOCATION is '设备位置';

comment on column RE_SCORE_QUARTER.FRACTIONRATIO is '评分加权分数';

comment on column RE_SCORE_QUARTER.SCORE is '季度平均分';

comment on column RE_SCORE_QUARTER.CREATETIME is '季度：如2020-1为2020年第一季度';

INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50.0000, '2020-1', 3590894);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (4, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 44.0000, '2019-4', 3647385);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (5, 'AH02', '中压开关设备', '35kV', 'A001', 0.0294, 90.0000, '2020-1', 3786071);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (6, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 70.0000, '2020-1', 3786072);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (7, 'AH04', '中压开关设备', '35kV', 'A001', 0.0294, 80.0000, '2020-1', 3786317);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (8, 'AH05', '中压开关设备', '35kV', 'A001', 0.0294, 70.0000, '2020-1', 3786316);
create table RE_SCORE_YEAR
(
    REMEDIUMVOLTAGESCOREYEARID BIGINT
        primary key,
    IEDNAME                    VARGRAPHIC(100),
    ASSETYPE                   VARGRAPHIC(100),
    SCORE                      DECIMAL(8, 4),
    CREATETIME                 VARGRAPHIC(100),
    ROWSTAMP                   BIGINT not null,
    PRODUCTMODEL               VARGRAPHIC(100),
    LOCATION                   VARGRAPHIC(100)
);

comment on table RE_SCORE_YEAR is '年度评分表';

comment on column RE_SCORE_YEAR.IEDNAME is '设备编码';

comment on column RE_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_SCORE_YEAR.SCORE is '得分';

comment on column RE_SCORE_YEAR.CREATETIME is '年度时间';

comment on column RE_SCORE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_YEAR.LOCATION is '位置';

INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (1, 'AH01', '中压开关设备', 50.0000, '2020', 3787993, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (2, 'AH01', '中压开关设备', 51.0000, '2019', 3787996, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (3, 'AH02', '中压开关设备', 100.0000, '2020', 3787995, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (4, 'AH03', '中压开关设备', 80.0000, '2020', 3787997, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (5, 'AH04', '中压开关设备', 90.0000, '2020', 3787994, '35kV', 'A001');
create table RE_TOTAL_COMPARE_QUARTER
(
    RETOTALCOMPAREQUARTERID BIGINT
        primary key,
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    SCORE                   DECIMAL(8, 4),
    CREATETIME              VARGRAPHIC(100),
    COMPARISON              VARGRAPHIC(50),
    RATIO                   DECIMAL(8, 4),
    ROWSTAMP                BIGINT not null
);

comment on table RE_TOTAL_COMPARE_QUARTER is '总体季度对比';

comment on column RE_TOTAL_COMPARE_QUARTER.RETOTALCOMPAREQUARTERID is '主键';

comment on column RE_TOTAL_COMPARE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_COMPARE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_COMPARE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_COMPARE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_COMPARE_QUARTER.CREATETIME is '季度时间';

comment on column RE_TOTAL_COMPARE_QUARTER.COMPARISON is '对比结果';

comment on column RE_TOTAL_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2', '有所下降', -0.1691, 3884468);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', '', 0.0000, 3884469);
create table RE_TOTAL_COMPARE_YEAR
(
    RETOTALCOMPAREYEARID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    SCORE                DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100),
    COMPARISON           VARGRAPHIC(50),
    RATIO                DECIMAL(8, 4),
    ROWSTAMP             BIGINT not null
);

comment on table RE_TOTAL_COMPARE_YEAR is '总体年度对比';

comment on column RE_TOTAL_COMPARE_YEAR.RETOTALCOMPAREYEARID is '主键';

comment on column RE_TOTAL_COMPARE_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_COMPARE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_COMPARE_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_COMPARE_YEAR.SCORE is '评分';

comment on column RE_TOTAL_COMPARE_YEAR.CREATETIME is '时间-年度';

comment on column RE_TOTAL_COMPARE_YEAR.COMPARISON is '对比结果';

comment on column RE_TOTAL_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_COMPARE_YEAR (RETOTALCOMPAREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 3.5000, '2019', '', 0.0000, 3885329);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_YEAR (RETOTALCOMPAREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 4.7377, '2020', '有所提升', 0.3536, 3885330);
create table RE_TOTAL_HEALTH_QUARTER
(
    RETOTALHEALTHQUARTERID BIGINT
        primary key,
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    EXCELLENT              INTEGER,
    GOOD                   INTEGER,
    RANGE                  INTEGER,
    CREATETIME             VARGRAPHIC(100),
    ROWSTAMP               BIGINT not null
);

comment on table RE_TOTAL_HEALTH_QUARTER is '季度健康度统计';

comment on column RE_TOTAL_HEALTH_QUARTER.RETOTALHEALTHQUARTERID is '主键';

comment on column RE_TOTAL_HEALTH_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_HEALTH_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_HEALTH_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_HEALTH_QUARTER.EXCELLENT is '优秀';

comment on column RE_TOTAL_HEALTH_QUARTER.GOOD is '良好';

comment on column RE_TOTAL_HEALTH_QUARTER.RANGE is '极差';

comment on column RE_TOTAL_HEALTH_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_HEALTH_QUARTER (RETOTALHEALTHQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 1, 3, 1, '2020-1', 3886191);
create table RE_TOTAL_HEALTH_YEAR
(
    RETOTALHEALTHYEARID BIGINT
        primary key,
    ASSETYPE            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    EXCELLENT           INTEGER,
    GOOD                INTEGER,
    RANGE               INTEGER,
    CREATETIME          VARGRAPHIC(100),
    ROWSTAMP            BIGINT not null
);

comment on table RE_TOTAL_HEALTH_YEAR is '年度健康度统计';

comment on column RE_TOTAL_HEALTH_YEAR.RETOTALHEALTHYEARID is '主键';

comment on column RE_TOTAL_HEALTH_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_HEALTH_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_HEALTH_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_HEALTH_YEAR.EXCELLENT is '优秀';

comment on column RE_TOTAL_HEALTH_YEAR.GOOD is '良好';

comment on column RE_TOTAL_HEALTH_YEAR.RANGE is '极差';

comment on column RE_TOTAL_HEALTH_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_HEALTH_YEAR (RETOTALHEALTHYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 2, 1, 1, '2020', 3887053);
create table RE_TOTAL_LOAD_QUARTER
(
    RETOTALLOADQUARTERID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    LOADFACTOR           DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100)
);

comment on table RE_TOTAL_LOAD_QUARTER is '总体中压开关柜季度负荷率';

comment on column RE_TOTAL_LOAD_QUARTER.RETOTALLOADQUARTERID is '主键';

comment on column RE_TOTAL_LOAD_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_TOTAL_LOAD_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_QUARTER (RETOTALLOADQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME) VALUES (3, '中压开关设备', '35kV', 'A001', 0.0018, '2020-1');
create table RE_TOTAL_LOAD_YEAR
(
    RETOTALLOADYEARID BIGINT
        primary key,
    ASSETYPE          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    LOADFACTOR        DECIMAL(8, 4),
    CREATETIME        VARGRAPHIC(100)
);

INSERT INTO MAXIMO.RE_TOTAL_LOAD_YEAR (RETOTALLOADYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME) VALUES (2, '中压开关设备', '35kV', 'A001', 0.0018, '2020');
create table RE_TOTAL_SCORE_MONTH
(
    RETOTALSCOREMONTHID BIGINT
        primary key,
    ASSETYPE            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    SCORE               DECIMAL(8, 4),
    CREATETIME          VARGRAPHIC(100),
    ROWSTAMP            BIGINT not null
);

comment on table RE_TOTAL_SCORE_MONTH is '总体月度评分';

comment on column RE_TOTAL_SCORE_MONTH.RETOTALSCOREMONTHID is '主键';

comment on column RE_TOTAL_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_MONTH.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_MONTH.SCORE is '评分';

comment on column RE_TOTAL_SCORE_MONTH.CREATETIME is '时间-月度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 4.8510, '2020-02', 3887916);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (4, '中压开关设备', '35kV', 'A001', 5.5000, '2020-01', 3887917);
create table RE_TOTAL_SCORE_QUARTER
(
    RETOTALSCOREQUARTERID BIGINT
        primary key,
    ASSETYPE              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    SCORE                 DECIMAL(8, 4),
    CREATETIME            VARGRAPHIC(100),
    ROWSTAMP              BIGINT not null
);

comment on table RE_TOTAL_SCORE_QUARTER is '总体季度评分';

comment on column RE_TOTAL_SCORE_QUARTER.RETOTALSCOREQUARTERID is '主键';

comment on column RE_TOTAL_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_SCORE_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2', 3888781);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', 3888782);
create table RE_TOTAL_SCORE_YEAR
(
    RETOTALSCOREYEARID BIGINT
        primary key,
    ASSETYPE           VARGRAPHIC(100),
    PRODUCTMODEL       VARGRAPHIC(100),
    LOCATION           VARGRAPHIC(100),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100),
    ROWSTAMP           BIGINT not null
);

comment on table RE_TOTAL_SCORE_YEAR is '总体年度评分';

comment on column RE_TOTAL_SCORE_YEAR.RETOTALSCOREYEARID is '主键';

comment on column RE_TOTAL_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_YEAR.SCORE is '评分';

comment on column RE_TOTAL_SCORE_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 4.7377, '2020', 3889647);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 3.5000, '2019', 3889648);