create table RE_TOTAL_SCORE_QUARTER
(
    RETOTALSCOREQUARTERID BIGINT
        primary key,
    ASSETYPE              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    SCORE                 DECIMAL(8, 4),
    CREATETIME            VARGRAPHIC(100)
);

comment on table RE_TOTAL_SCORE_QUARTER is '总体季度评分';

comment on column RE_TOTAL_SCORE_QUARTER.RETOTALSCOREQUARTERID is '主键';

comment on column RE_TOTAL_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_SCORE_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (3, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2');
INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (2, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1');