create table RE_SCORE_QUARTER
(
    REMEDIUMVOLTAGESCOREQUARTERID BIGINT
        primary key,
    IEDNAME                       VARGRAPHIC(100),
    ASSETYPE                      VARGRAPHIC(100),
    PRODUCTMODEL                  VARGRAPHIC(100),
    LOCATION                      VARGRAPHIC(100),
    FRACTIONRATIO                 DECIMAL(31, 4),
    SCORE                         DECIMAL(8, 4),
    CREATETIME                    VARGRAPHIC(100),
    ROWSTAMP                      BIGINT not null
);

comment on table RE_SCORE_QUARTER is '季度评分表';

comment on column RE_SCORE_QUARTER.IEDNAME is '设备编号';

comment on column RE_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_QUARTER.LOCATION is '设备位置';

comment on column RE_SCORE_QUARTER.FRACTIONRATIO is '评分加权分数';

comment on column RE_SCORE_QUARTER.SCORE is '季度平均分';

comment on column RE_SCORE_QUARTER.CREATETIME is '季度：如2020-1为2020年第一季度';

INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50.0000, '2020-1', 3590894);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (4, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 44.0000, '2019-4', 3647385);