create table RE_TOTAL_SCORE_MONTH
(
    RETOTALSCOREMONTHID BIGINT
        primary key,
    ASSETYPE            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    SCORE               DECIMAL(8, 4),
    CREATETIME          VARGRAPHIC(100)
);

comment on table RE_TOTAL_SCORE_MONTH is '总体月度评分';

comment on column RE_TOTAL_SCORE_MONTH.RETOTALSCOREMONTHID is '主键';

comment on column RE_TOTAL_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_MONTH.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_MONTH.SCORE is '评分';

comment on column RE_TOTAL_SCORE_MONTH.CREATETIME is '时间-月度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (3, '中压开关设备', '35kV', 'A001', 4.8510, '2020-02');
INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (4, '中压开关设备', '35kV', 'A001', 5.5000, '2020-01');