create table RE_ALL_VOL_EM_COMP_QUARTER
(
    REALLVOLEMCOMPQUARTERID BIGINT
        primary key,
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    PRODUCTMODELC           VARGRAPHIC(100),
    ELECTRICDEGREE          DECIMAL(31, 4),
    CREATETIME              VARGRAPHIC(100),
    COMPARISON              VARGRAPHIC(50),
    RATIO                   DECIMAL(8, 4)
);

comment on table RE_ALL_VOL_EM_COMP_QUARTER is '整体中压设备-季度总电度量比对';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.REALLVOLEMCOMPQUARTERID is '主键';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.ASSETYPE is '设备类别';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.LOCATION is '位置';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.PRODUCTMODELC is '段信息';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.ELECTRICDEGREE is '总电度量';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.CREATETIME is '时间-季度';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.COMPARISON is '对比结果';

comment on column RE_ALL_VOL_EM_COMP_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_ALL_VOL_EM_COMP_QUARTER (REALLVOLEMCOMPQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ELECTRICDEGREE, CREATETIME, COMPARISON, RATIO) VALUES (1, '中压开关设备', '35kV', 'A001', 'I段', 13.0000, '2020-1', '有所提升', 0.4444);
create table RE_ALL_VOL_EM_COMP_YEAR
(
    REALLVOLEMCOMPYEARID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    PRODUCTMODELC        VARGRAPHIC(100),
    ELECTRICDEGREE       DECIMAL(31, 4),
    CREATETIME           VARGRAPHIC(100),
    COMPARISON           VARGRAPHIC(50),
    RATIO                DECIMAL(8, 4)
);

comment on table RE_ALL_VOL_EM_COMP_YEAR is '整体中压设备-年度总电度量比对';

comment on column RE_ALL_VOL_EM_COMP_YEAR.REALLVOLEMCOMPYEARID is '主键';

comment on column RE_ALL_VOL_EM_COMP_YEAR.ASSETYPE is '设备类别';

comment on column RE_ALL_VOL_EM_COMP_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_ALL_VOL_EM_COMP_YEAR.LOCATION is '位置';

comment on column RE_ALL_VOL_EM_COMP_YEAR.PRODUCTMODELC is '段信息';

comment on column RE_ALL_VOL_EM_COMP_YEAR.ELECTRICDEGREE is '总电度量';

comment on column RE_ALL_VOL_EM_COMP_YEAR.CREATETIME is '时间-年度';

comment on column RE_ALL_VOL_EM_COMP_YEAR.COMPARISON is '对比结果';

comment on column RE_ALL_VOL_EM_COMP_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_ALL_VOL_EM_COMP_YEAR (REALLVOLEMCOMPYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ELECTRICDEGREE, CREATETIME, COMPARISON, RATIO) VALUES (1, '中压开关设备', '35kV', 'A001', 'I段', 8.0000, '2019', '', 0.0000);
INSERT INTO MAXIMO.RE_ALL_VOL_EM_COMP_YEAR (REALLVOLEMCOMPYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ELECTRICDEGREE, CREATETIME, COMPARISON, RATIO) VALUES (2, '中压开关设备', '35kV', 'A001', 'I段', 16.0000, '2020', '有所提升', 1.0000);
create table RE_ALL_VOLTAGE_EM_QUARTER
(
    REALLVOLTAGEEMQUARTERID BIGINT
        primary key,
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    PRODUCTMODELC           VARGRAPHIC(100),
    ACTIVEELECTRICDEGREE    DECIMAL(31, 4),
    REACTIVEELECTRICDEGREE  DECIMAL(31, 4),
    CREATETIME              VARGRAPHIC(50),
    ELECTRICDEGREE          DECIMAL(31, 4),
    REACTIVEPERCENT         DECIMAL(31, 4),
    OPINION                 VARGRAPHIC(50)
);

comment on table RE_ALL_VOLTAGE_EM_QUARTER is '整体中压设备季度有功电度量和无功电度量';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.ASSETYPE is '设备类别';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.LOCATION is '位置';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.PRODUCTMODELC is '段信息';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.ACTIVEELECTRICDEGREE is '有功电度量';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.REACTIVEELECTRICDEGREE is '无功电度量';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.CREATETIME is '时间-季度';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.ELECTRICDEGREE is '总点度量';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.REACTIVEPERCENT is '无功电度量占总电度比例';

comment on column RE_ALL_VOLTAGE_EM_QUARTER.OPINION is '意见';

INSERT INTO MAXIMO.RE_ALL_VOLTAGE_EM_QUARTER (REALLVOLTAGEEMQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION) VALUES (1, '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 2.0000, '2020-1', 13.0000, 0.1538, '合理');
INSERT INTO MAXIMO.RE_ALL_VOLTAGE_EM_QUARTER (REALLVOLTAGEEMQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION) VALUES (2, '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 2.0000, '2019-4', 9.0000, 0.1538, '合理');
create table RE_ALL_VOLTAGE_EM_YEAR
(
    REALLVOLTAGEEMYEARID   BIGINT
        primary key,
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    PRODUCTMODELC          VARGRAPHIC(100),
    ACTIVEELECTRICDEGREE   DECIMAL(31, 4),
    REACTIVEELECTRICDEGREE DECIMAL(31, 4),
    CREATETIME             VARGRAPHIC(50),
    ELECTRICDEGREE         DECIMAL(31, 4),
    REACTIVEPERCENT        DECIMAL(31, 4),
    OPINION                VARGRAPHIC(50)
);

comment on table RE_ALL_VOLTAGE_EM_YEAR is '整体中压设备年度有功电度量和无功电度量';

comment on column RE_ALL_VOLTAGE_EM_YEAR.ASSETYPE is '设备类别';

comment on column RE_ALL_VOLTAGE_EM_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_ALL_VOLTAGE_EM_YEAR.LOCATION is '位置';

comment on column RE_ALL_VOLTAGE_EM_YEAR.PRODUCTMODELC is '段信息';

comment on column RE_ALL_VOLTAGE_EM_YEAR.ACTIVEELECTRICDEGREE is '有功电度量';

comment on column RE_ALL_VOLTAGE_EM_YEAR.REACTIVEELECTRICDEGREE is '无功电度量';

comment on column RE_ALL_VOLTAGE_EM_YEAR.CREATETIME is '时间-季度';

comment on column RE_ALL_VOLTAGE_EM_YEAR.ELECTRICDEGREE is '总点度量';

comment on column RE_ALL_VOLTAGE_EM_YEAR.REACTIVEPERCENT is '无功电度量占总电度比例';

comment on column RE_ALL_VOLTAGE_EM_YEAR.OPINION is '意见';

INSERT INTO MAXIMO.RE_ALL_VOLTAGE_EM_YEAR (REALLVOLTAGEEMYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION) VALUES (1, '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 1.0000, '2020', 16.0000, 0.0625, '合理');
INSERT INTO MAXIMO.RE_ALL_VOLTAGE_EM_YEAR (REALLVOLTAGEEMYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION) VALUES (2, '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 2.0000, '2019', 8.0000, 0.0700, '合理');
create table RE_COMPARE_QUARTER
(
    RECOMPAREQUARTERID BIGINT
        primary key,
    IEDNAME            VARGRAPHIC(100),
    ASSETYPE           VARGRAPHIC(100),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100),
    COMPARISON         VARGRAPHIC(50),
    RATIO              DECIMAL(8, 4),
    ROWSTAMP           BIGINT not null
);

comment on table RE_COMPARE_QUARTER is '季度对比及变化率表';

comment on column RE_COMPARE_QUARTER.IEDNAME is '设备编码';

comment on column RE_COMPARE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_COMPARE_QUARTER.SCORE is '得分';

comment on column RE_COMPARE_QUARTER.CREATETIME is '时间';

comment on column RE_COMPARE_QUARTER.COMPARISON is '对比上季度';

comment on column RE_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (21, 'AH01', '中压开关设备', 50.0000, '2020-1', '大致持平', 0.0000, 5083583);
INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, 'AH01', '中压开关设备', 50.0000, '2020-1', '有所提升', 0.1363, 3707049);
INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (22, 'AH02', '中压开关设备', 60.0000, '2020-1', '有所下降', -0.3333, 5083584);
INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (23, 'AH03', '中压开关设备', 55.0000, '2020-1', '有所下降', -0.2142, 5083585);
INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (24, 'AH04', '中压开关设备', 80.0000, '2020-1', '', 0.0000, 5083586);
INSERT INTO MAXIMO.RE_COMPARE_QUARTER (RECOMPAREQUARTERID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (25, 'AH05', '中压开关设备', 70.0000, '2020-1', '', 0.0000, 5083587);
create table RE_COMPARE_YEAR
(
    RECOMPAREYEARID BIGINT
        primary key,
    IEDNAME         VARGRAPHIC(100),
    ASSETYPE        VARGRAPHIC(100),
    SCORE           DECIMAL(8, 4),
    CREATETIME      VARGRAPHIC(100),
    COMPARISON      VARGRAPHIC(50),
    RATIO           DECIMAL(8, 4),
    ROWSTAMP        BIGINT not null
);

comment on table RE_COMPARE_YEAR is '年度对比及变化率表';

comment on column RE_COMPARE_YEAR.RECOMPAREYEARID is '主键';

comment on column RE_COMPARE_YEAR.IEDNAME is '设备编码';

comment on column RE_COMPARE_YEAR.ASSETYPE is '设备类别';

comment on column RE_COMPARE_YEAR.SCORE is '得分';

comment on column RE_COMPARE_YEAR.CREATETIME is '年份时间';

comment on column RE_COMPARE_YEAR.COMPARISON is '对比结果';

comment on column RE_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_COMPARE_YEAR (RECOMPAREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', 50.0000, '2020', '有所提升', 0.6666, 3707906);
create table RE_LOAD_COMPARE_QUARTER
(
    RELOADCOMPAREQUARTERID BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    LOADFACTOR             DECIMAL(31, 4),
    CREATETIME             VARGRAPHIC(100),
    COMPARISON             VARGRAPHIC(50),
    RATIO                  DECIMAL(31, 4),
    ROWSTAMP               BIGINT not null
);

comment on table RE_LOAD_COMPARE_QUARTER is '单台中压开关柜负荷率季度比对';

comment on column RE_LOAD_COMPARE_QUARTER.RELOADCOMPAREQUARTERID is '主键';

comment on column RE_LOAD_COMPARE_QUARTER.IEDNAME is '设备编码';

comment on column RE_LOAD_COMPARE_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_LOAD_COMPARE_QUARTER.CREATETIME is '时间-季度';

comment on column RE_LOAD_COMPARE_QUARTER.COMPARISON is '对比结果';

comment on column RE_LOAD_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_LOAD_COMPARE_QUARTER (RELOADCOMPAREQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (3, 'AH01', 0.0018, '2020-1', '有所下降', -0.4000, 4337105);
INSERT INTO MAXIMO.RE_LOAD_COMPARE_QUARTER (RELOADCOMPAREQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (4, 'AH01', 0.0030, '2019-4', '', 0.0000, 4337106);
INSERT INTO MAXIMO.RE_LOAD_COMPARE_QUARTER (RELOADCOMPAREQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (21, 'AH01', 0.0018, '2020-1', '大致持平', 0.0000, 5086734);
create table RE_LOAD_COMPARE_YEAR
(
    RELOADCOMPAREYEARID BIGINT
        primary key,
    IEDNAME             VARGRAPHIC(100),
    LOADFACTOR          DECIMAL(31, 4),
    CREATETIME          VARGRAPHIC(100),
    COMPARISON          VARGRAPHIC(50),
    RATIO               DECIMAL(31, 4),
    ROWSTAMP            BIGINT not null
);

comment on table RE_LOAD_COMPARE_YEAR is '单台中压开关柜负荷率年度比对';

comment on column RE_LOAD_COMPARE_YEAR.RELOADCOMPAREYEARID is '主键';

comment on column RE_LOAD_COMPARE_YEAR.IEDNAME is '设备编码';

comment on column RE_LOAD_COMPARE_YEAR.LOADFACTOR is '负荷率';

comment on column RE_LOAD_COMPARE_YEAR.CREATETIME is '时间-年度';

comment on column RE_LOAD_COMPARE_YEAR.COMPARISON is '对比往年结果';

comment on column RE_LOAD_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_LOAD_COMPARE_YEAR (RELOADCOMPAREYEARID, IEDNAME, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, 'AH01', 0.0018, '2020', '有所下降', -0.1000, 4337973);
create table RE_LOAD_QUARTER
(
    RELOADQUARTERID BIGINT
        primary key,
    IEDNAME         VARGRAPHIC(100),
    LOADFACTOR      DECIMAL(31, 4),
    CREATETIME      VARGRAPHIC(100),
    ASSETYPE        VARGRAPHIC(100),
    PRODUCTMODEL    VARGRAPHIC(100),
    LOCATION        VARGRAPHIC(100),
    ROWSTAMP        BIGINT not null
);

comment on table RE_LOAD_QUARTER is '单台开关柜负荷率-季度';

comment on column RE_LOAD_QUARTER.RELOADQUARTERID is '主键';

comment on column RE_LOAD_QUARTER.IEDNAME is '设备编码';

comment on column RE_LOAD_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_LOAD_QUARTER.CREATETIME is '时间-季度';

comment on column RE_LOAD_QUARTER.ASSETYPE is '设备类别';

comment on column RE_LOAD_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_LOAD_QUARTER.LOCATION is '位置';

INSERT INTO MAXIMO.RE_LOAD_QUARTER (RELOADQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, ASSETYPE, PRODUCTMODEL, LOCATION, ROWSTAMP) VALUES (2, 'AH01', 0.0030, '2019-4', '中压开关设备', '35kV', 'A001', 4338841);
INSERT INTO MAXIMO.RE_LOAD_QUARTER (RELOADQUARTERID, IEDNAME, LOADFACTOR, CREATETIME, ASSETYPE, PRODUCTMODEL, LOCATION, ROWSTAMP) VALUES (22, 'AH01', 0.0018, '2020-1', '中压开关设备', '35kV', 'A001', 5226231);
create table RE_LOAD_YEAR
(
    RELOADYEARID BIGINT
        primary key,
    IEDNAME      VARGRAPHIC(100),
    LOADFACTOR   DECIMAL(31, 4),
    CREATETIME   VARGRAPHIC(100),
    ASSETYPE     VARGRAPHIC(100),
    PRODUCTMODEL VARGRAPHIC(100),
    LOCATION     VARGRAPHIC(100),
    ROWSTAMP     BIGINT not null
);

comment on table RE_LOAD_YEAR is '单台开关柜负荷率-年度';

comment on column RE_LOAD_YEAR.RELOADYEARID is '主键';

comment on column RE_LOAD_YEAR.IEDNAME is '设备编码';

comment on column RE_LOAD_YEAR.LOADFACTOR is '负荷率';

comment on column RE_LOAD_YEAR.CREATETIME is '时间-年度';

comment on column RE_LOAD_YEAR.ASSETYPE is '设备类别';

comment on column RE_LOAD_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_LOAD_YEAR.LOCATION is '位置';

INSERT INTO MAXIMO.RE_LOAD_YEAR (RELOADYEARID, IEDNAME, LOADFACTOR, CREATETIME, ASSETYPE, PRODUCTMODEL, LOCATION, ROWSTAMP) VALUES (3, 'AH01', 0.0020, '2019', '中压开关设备', '35kV', 'A001', 4339711);
INSERT INTO MAXIMO.RE_LOAD_YEAR (RELOADYEARID, IEDNAME, LOADFACTOR, CREATETIME, ASSETYPE, PRODUCTMODEL, LOCATION, ROWSTAMP) VALUES (5, 'AH01', 0.0018, '2020', '中压开关设备', '35kV', 'A001', 4339712);
create table RE_SCORE_MONTH
(
    REMEDIUMVOLTAGESCOREID BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    FRACTIONRATIO          DECIMAL(31, 4),
    SCORE                  INTEGER,
    CREATETIME             VARGRAPHIC(100),
    ROWSTAMP               BIGINT not null
);

comment on table RE_SCORE_MONTH is '评分表';

comment on column RE_SCORE_MONTH.REMEDIUMVOLTAGESCOREID is '主键';

comment on column RE_SCORE_MONTH.IEDNAME is '设备编码';

comment on column RE_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_MONTH.LOCATION is '位置';

comment on column RE_SCORE_MONTH.FRACTIONRATIO is '评分系数';

comment on column RE_SCORE_MONTH.SCORE is '评分';

comment on column RE_SCORE_MONTH.CREATETIME is '时间月份';

INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50, '2020-02', 4340595);
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (4, 'AH02', '中压开关设备', '35kV', 'A001', 0.0294, 60, '2020-02', 4340596);
INSERT INTO MAXIMO.RE_SCORE_MONTH (REMEDIUMVOLTAGESCOREID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (5, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 55, '2020-02', 4340597);
create table RE_SCORE_QUARTER
(
    REMEDIUMVOLTAGESCOREQUARTERID BIGINT
        primary key,
    IEDNAME                       VARGRAPHIC(100),
    ASSETYPE                      VARGRAPHIC(100),
    PRODUCTMODEL                  VARGRAPHIC(100),
    LOCATION                      VARGRAPHIC(100),
    FRACTIONRATIO                 DECIMAL(31, 4),
    SCORE                         DECIMAL(8, 4),
    CREATETIME                    VARGRAPHIC(100),
    ROWSTAMP                      BIGINT not null
);

comment on table RE_SCORE_QUARTER is '季度评分表';

comment on column RE_SCORE_QUARTER.IEDNAME is '设备编号';

comment on column RE_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_QUARTER.LOCATION is '设备位置';

comment on column RE_SCORE_QUARTER.FRACTIONRATIO is '评分加权分数';

comment on column RE_SCORE_QUARTER.SCORE is '季度平均分';

comment on column RE_SCORE_QUARTER.CREATETIME is '季度：如2020-1为2020年第一季度';

INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50.0000, '2020-1', 3590894);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (4, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 44.0000, '2019-4', 3647385);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (5, 'AH02', '中压开关设备', '35kV', 'A001', 0.0294, 90.0000, '2020-1', 3786071);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (6, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 70.0000, '2020-1', 3786072);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (7, 'AH04', '中压开关设备', '35kV', 'A001', 0.0294, 80.0000, '2020-1', 3786317);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (8, 'AH05', '中压开关设备', '35kV', 'A001', 0.0294, 70.0000, '2020-1', 3786316);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (21, 'AH01', '中压开关设备', '35kV', 'A001', 0.0294, 50.0000, '2020-1', 5080347);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (22, 'AH02', '中压开关设备', '35kV', 'A001', 0.2000, 60.0000, '2020-1', 5080348);
INSERT INTO MAXIMO.RE_SCORE_QUARTER (REMEDIUMVOLTAGESCOREQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, FRACTIONRATIO, SCORE, CREATETIME, ROWSTAMP) VALUES (23, 'AH03', '中压开关设备', '35kV', 'A001', 0.0294, 55.0000, '2020-1', 5080349);
create table RE_SCORE_YEAR
(
    REMEDIUMVOLTAGESCOREYEARID BIGINT
        primary key,
    IEDNAME                    VARGRAPHIC(100),
    ASSETYPE                   VARGRAPHIC(100),
    SCORE                      DECIMAL(8, 4),
    CREATETIME                 VARGRAPHIC(100),
    ROWSTAMP                   BIGINT not null,
    PRODUCTMODEL               VARGRAPHIC(100),
    LOCATION                   VARGRAPHIC(100)
);

comment on table RE_SCORE_YEAR is '年度评分表';

comment on column RE_SCORE_YEAR.IEDNAME is '设备编码';

comment on column RE_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_SCORE_YEAR.SCORE is '得分';

comment on column RE_SCORE_YEAR.CREATETIME is '年度时间';

comment on column RE_SCORE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_SCORE_YEAR.LOCATION is '位置';

INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (1, 'AH01', '中压开关设备', 50.0000, '2020', 3787993, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (2, 'AH01', '中压开关设备', 51.0000, '2019', 3787996, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (3, 'AH02', '中压开关设备', 100.0000, '2020', 3787995, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (4, 'AH03', '中压开关设备', 80.0000, '2020', 3787997, '35kV', 'A001');
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP, PRODUCTMODEL, LOCATION) VALUES (5, 'AH04', '中压开关设备', 90.0000, '2020', 3787994, '35kV', 'A001');
create table RE_TOTAL_COMPARE_QUARTER
(
    RETOTALCOMPAREQUARTERID BIGINT
        primary key,
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    SCORE                   DECIMAL(8, 4),
    CREATETIME              VARGRAPHIC(100),
    COMPARISON              VARGRAPHIC(50),
    RATIO                   DECIMAL(8, 4),
    ROWSTAMP                BIGINT not null
);

comment on table RE_TOTAL_COMPARE_QUARTER is '总体季度对比';

comment on column RE_TOTAL_COMPARE_QUARTER.RETOTALCOMPAREQUARTERID is '主键';

comment on column RE_TOTAL_COMPARE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_COMPARE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_COMPARE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_COMPARE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_COMPARE_QUARTER.CREATETIME is '季度时间';

comment on column RE_TOTAL_COMPARE_QUARTER.COMPARISON is '对比结果';

comment on column RE_TOTAL_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2', '有所下降', -0.1691, 3884468);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', '', 0.0000, 3884469);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (21, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', '', 0.0000, 5085214);
create table RE_TOTAL_COMPARE_YEAR
(
    RETOTALCOMPAREYEARID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    SCORE                DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100),
    COMPARISON           VARGRAPHIC(50),
    RATIO                DECIMAL(8, 4),
    ROWSTAMP             BIGINT not null
);

comment on table RE_TOTAL_COMPARE_YEAR is '总体年度对比';

comment on column RE_TOTAL_COMPARE_YEAR.RETOTALCOMPAREYEARID is '主键';

comment on column RE_TOTAL_COMPARE_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_COMPARE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_COMPARE_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_COMPARE_YEAR.SCORE is '评分';

comment on column RE_TOTAL_COMPARE_YEAR.CREATETIME is '时间-年度';

comment on column RE_TOTAL_COMPARE_YEAR.COMPARISON is '对比结果';

comment on column RE_TOTAL_COMPARE_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_COMPARE_YEAR (RETOTALCOMPAREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 3.5000, '2019', '', 0.0000, 3885329);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_YEAR (RETOTALCOMPAREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 4.7377, '2020', '有所提升', 0.3536, 3885330);
create table RE_TOTAL_HEALTH_QUARTER
(
    RETOTALHEALTHQUARTERID BIGINT
        primary key,
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    EXCELLENT              INTEGER,
    GOOD                   INTEGER,
    RANGE                  INTEGER,
    CREATETIME             VARGRAPHIC(100),
    ROWSTAMP               BIGINT not null
);

comment on table RE_TOTAL_HEALTH_QUARTER is '季度健康度统计';

comment on column RE_TOTAL_HEALTH_QUARTER.RETOTALHEALTHQUARTERID is '主键';

comment on column RE_TOTAL_HEALTH_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_HEALTH_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_HEALTH_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_HEALTH_QUARTER.EXCELLENT is '优秀';

comment on column RE_TOTAL_HEALTH_QUARTER.GOOD is '良好';

comment on column RE_TOTAL_HEALTH_QUARTER.RANGE is '极差';

comment on column RE_TOTAL_HEALTH_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_HEALTH_QUARTER (RETOTALHEALTHQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 1, 3, 1, '2020-1', 3886191);
INSERT INTO MAXIMO.RE_TOTAL_HEALTH_QUARTER (RETOTALHEALTHQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME, ROWSTAMP) VALUES (21, '中压开关设备', '35kV', 'A001', 1, 3, 4, '2020-1', 5086024);
create table RE_TOTAL_HEALTH_YEAR
(
    RETOTALHEALTHYEARID BIGINT
        primary key,
    ASSETYPE            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    EXCELLENT           INTEGER,
    GOOD                INTEGER,
    RANGE               INTEGER,
    CREATETIME          VARGRAPHIC(100),
    ROWSTAMP            BIGINT not null
);

comment on table RE_TOTAL_HEALTH_YEAR is '年度健康度统计';

comment on column RE_TOTAL_HEALTH_YEAR.RETOTALHEALTHYEARID is '主键';

comment on column RE_TOTAL_HEALTH_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_HEALTH_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_HEALTH_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_HEALTH_YEAR.EXCELLENT is '优秀';

comment on column RE_TOTAL_HEALTH_YEAR.GOOD is '良好';

comment on column RE_TOTAL_HEALTH_YEAR.RANGE is '极差';

comment on column RE_TOTAL_HEALTH_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_HEALTH_YEAR (RETOTALHEALTHYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 2, 1, 1, '2020', 3887053);
create table RE_TOTAL_LOAD_COMP_QUARTER
(
    RETOTALLOADCOMPAREQUARTERID BIGINT
        primary key,
    ASSETYPE                    VARGRAPHIC(100),
    PRODUCTMODEL                VARGRAPHIC(100),
    LOCATION                    VARGRAPHIC(100),
    LOADFACTOR                  DECIMAL(8, 4),
    CREATETIME                  VARGRAPHIC(100),
    COMPARISON                  VARGRAPHIC(50),
    RATIO                       DECIMAL(8, 4),
    ROWSTAMP                    BIGINT not null
);

comment on table RE_TOTAL_LOAD_COMP_QUARTER is '季度负荷率对比';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.RETOTALLOADCOMPAREQUARTERID is '主键';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.CREATETIME is '时间-季度';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.COMPARISON is '对比结果';

comment on column RE_TOTAL_LOAD_COMP_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_COMP_QUARTER (RETOTALLOADCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (8, '中压开关设备', '35kV', 'A001', 0.0018, '2020-1', '有所下降', -0.1000, 4341470);
create table RE_TOTAL_LOAD_COMP_YEAR
(
    RETOTALLOADCOMPAREYEARID BIGINT
        primary key,
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    LOADFACTOR               DECIMAL(8, 4),
    CREATETIME               VARGRAPHIC(100),
    COMPARISON               VARGRAPHIC(50),
    RATIO                    DECIMAL(8, 4),
    ROWSTAMP                 BIGINT not null
);

comment on table RE_TOTAL_LOAD_COMP_YEAR is '年度负荷率对比';

comment on column RE_TOTAL_LOAD_COMP_YEAR.RETOTALLOADCOMPAREYEARID is '主键';

comment on column RE_TOTAL_LOAD_COMP_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_COMP_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_COMP_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_COMP_YEAR.LOADFACTOR is '负荷率';

comment on column RE_TOTAL_LOAD_COMP_YEAR.CREATETIME is '时间-年度';

comment on column RE_TOTAL_LOAD_COMP_YEAR.COMPARISON is '对比结果';

comment on column RE_TOTAL_LOAD_COMP_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_COMP_YEAR (RETOTALLOADCOMPAREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 0.0018, '2020', '有所提升', 0.7999, 4342342);
create table RE_TOTAL_LOAD_HEALTH_QUARTER
(
    RETOTALLOADHEALTHQUARTERID BIGINT
        primary key,
    ASSETYPE                   VARGRAPHIC(100),
    PRODUCTMODEL               VARGRAPHIC(100),
    LOCATION                   VARGRAPHIC(100),
    EXCELLENT                  INTEGER,
    GOOD                       INTEGER,
    RANGE                      INTEGER,
    CREATETIME                 VARGRAPHIC(100)
);

comment on table RE_TOTAL_LOAD_HEALTH_QUARTER is '季度负荷率评分统计';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.RETOTALLOADHEALTHQUARTERID is '主键';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.EXCELLENT is '优秀';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.GOOD is '良好';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.RANGE is '极差';

comment on column RE_TOTAL_LOAD_HEALTH_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_HEALTH_QUARTER (RETOTALLOADHEALTHQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME) VALUES (21, '中压开关设备', '35kV', 'A001', 2, 0, 0, '2020-1');
INSERT INTO MAXIMO.RE_TOTAL_LOAD_HEALTH_QUARTER (RETOTALLOADHEALTHQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME) VALUES (2, '中压开关设备', '35kV', 'A001', 1, 0, 0, '2020-1');
create table RE_TOTAL_LOAD_HEALTH_YEAR
(
    RETOTALLOADHEALTHYEAR BIGINT
        primary key,
    ASSETYPE              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    EXCELLENT             INTEGER,
    GOOD                  INTEGER,
    RANGE                 INTEGER,
    CREATETIME            VARGRAPHIC(100)
);

comment on table RE_TOTAL_LOAD_HEALTH_YEAR is '年度负荷率评分统计';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.RETOTALLOADHEALTHYEAR is '主键';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.EXCELLENT is '优秀';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.GOOD is '良好';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.RANGE is '极差';

comment on column RE_TOTAL_LOAD_HEALTH_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_HEALTH_YEAR (RETOTALLOADHEALTHYEAR, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME) VALUES (1, '中压开关设备', '35kV', 'A001', 1, 0, 0, '2019');
INSERT INTO MAXIMO.RE_TOTAL_LOAD_HEALTH_YEAR (RETOTALLOADHEALTHYEAR, ASSETYPE, PRODUCTMODEL, LOCATION, EXCELLENT, GOOD, RANGE, CREATETIME) VALUES (3, '中压开关设备', '35kV', 'A001', 1, 0, 0, '2020');
create table RE_TOTAL_LOAD_QUARTER
(
    RETOTALLOADQUARTERID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    LOADFACTOR           DECIMAL(8, 4),
    CREATETIME           VARGRAPHIC(100),
    ROWSTAMP             BIGINT not null
);

comment on table RE_TOTAL_LOAD_QUARTER is '总体中压开关柜季度负荷率';

comment on column RE_TOTAL_LOAD_QUARTER.RETOTALLOADQUARTERID is '主键';

comment on column RE_TOTAL_LOAD_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_QUARTER.LOADFACTOR is '负荷率';

comment on column RE_TOTAL_LOAD_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_QUARTER (RETOTALLOADQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, ROWSTAMP) VALUES (5, '中压开关设备', '35kV', 'A001', 0.0020, '2019-4', 4343215);
INSERT INTO MAXIMO.RE_TOTAL_LOAD_QUARTER (RETOTALLOADQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, ROWSTAMP) VALUES (21, '中压开关设备', '35kV', 'A001', 0.0000, '2020-1', 5086215);
INSERT INTO MAXIMO.RE_TOTAL_LOAD_QUARTER (RETOTALLOADQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, ROWSTAMP) VALUES (10, '中压开关设备', '35kV', 'A001', 0.0016, '2020-1', 4343216);
create table RE_TOTAL_LOAD_YEAR
(
    RETOTALLOADYEARID BIGINT
        primary key,
    ASSETYPE          VARGRAPHIC(100),
    PRODUCTMODEL      VARGRAPHIC(100),
    LOCATION          VARGRAPHIC(100),
    LOADFACTOR        DECIMAL(8, 4),
    CREATETIME        VARGRAPHIC(100),
    ROWSTAMP          BIGINT not null
);

comment on table RE_TOTAL_LOAD_YEAR is '总体中压开关柜年度负荷率';

comment on column RE_TOTAL_LOAD_YEAR.RETOTALLOADYEARID is '主键';

comment on column RE_TOTAL_LOAD_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_LOAD_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_LOAD_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_LOAD_YEAR.LOADFACTOR is '负荷率';

comment on column RE_TOTAL_LOAD_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_LOAD_YEAR (RETOTALLOADYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 0.0010, '2019', 4344090);
INSERT INTO MAXIMO.RE_TOTAL_LOAD_YEAR (RETOTALLOADYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, LOADFACTOR, CREATETIME, ROWSTAMP) VALUES (4, '中压开关设备', '35kV', 'A001', 0.0157, '2020', 4344091);
create table RE_TOTAL_SCORE_MONTH
(
    RETOTALSCOREMONTHID BIGINT
        primary key,
    ASSETYPE            VARGRAPHIC(100),
    PRODUCTMODEL        VARGRAPHIC(100),
    LOCATION            VARGRAPHIC(100),
    SCORE               DECIMAL(8, 4),
    CREATETIME          VARGRAPHIC(100),
    ROWSTAMP            BIGINT not null
);

comment on table RE_TOTAL_SCORE_MONTH is '总体月度评分';

comment on column RE_TOTAL_SCORE_MONTH.RETOTALSCOREMONTHID is '主键';

comment on column RE_TOTAL_SCORE_MONTH.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_MONTH.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_MONTH.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_MONTH.SCORE is '评分';

comment on column RE_TOTAL_SCORE_MONTH.CREATETIME is '时间-月度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 4.8510, '2020-02', 3887916);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_MONTH (RETOTALSCOREMONTHID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (4, '中压开关设备', '35kV', 'A001', 5.5000, '2020-01', 3887917);
create table RE_TOTAL_SCORE_QUARTER
(
    RETOTALSCOREQUARTERID BIGINT
        primary key,
    ASSETYPE              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    SCORE                 DECIMAL(8, 4),
    CREATETIME            VARGRAPHIC(100),
    ROWSTAMP              BIGINT not null
);

comment on table RE_TOTAL_SCORE_QUARTER is '总体季度评分';

comment on column RE_TOTAL_SCORE_QUARTER.RETOTALSCOREQUARTERID is '主键';

comment on column RE_TOTAL_SCORE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_SCORE_QUARTER.CREATETIME is '时间-季度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2', 3888781);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_QUARTER (RETOTALSCOREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', 3888782);
create table RE_TOTAL_SCORE_YEAR
(
    RETOTALSCOREYEARID BIGINT
        primary key,
    ASSETYPE           VARGRAPHIC(100),
    PRODUCTMODEL       VARGRAPHIC(100),
    LOCATION           VARGRAPHIC(100),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100),
    ROWSTAMP           BIGINT not null
);

comment on table RE_TOTAL_SCORE_YEAR is '总体年度评分';

comment on column RE_TOTAL_SCORE_YEAR.RETOTALSCOREYEARID is '主键';

comment on column RE_TOTAL_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_YEAR.SCORE is '评分';

comment on column RE_TOTAL_SCORE_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (1, '中压开关设备', '35kV', 'A001', 4.7377, '2020', 3889647);
INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 3.5000, '2019', 3889648);
create table RE_VOLTAGE_CONDITION
(
    REVOLTAGECONDITIONID BIGINT
        primary key,
    ASSETYPE             VARGRAPHIC(100),
    PRODUCTMODEL         VARGRAPHIC(100),
    LOCATION             VARGRAPHIC(100),
    PRODUCTMODELC        VARGRAPHIC(100),
    VOLTAGECONDITION     DECIMAL(8, 4),
    TIMEPOINT            VARGRAPHIC(50),
    CREATETIME           TIMESTAMP(6),
    ROWSTAMP             BIGINT not null
);

comment on table RE_VOLTAGE_CONDITION is '开关柜电压状况';

comment on column RE_VOLTAGE_CONDITION.REVOLTAGECONDITIONID is '主键';

comment on column RE_VOLTAGE_CONDITION.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_CONDITION.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_CONDITION.LOCATION is '位置';

comment on column RE_VOLTAGE_CONDITION.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_CONDITION.VOLTAGECONDITION is '电压状况';

comment on column RE_VOLTAGE_CONDITION.TIMEPOINT is '采集时间点';

comment on column RE_VOLTAGE_CONDITION.CREATETIME is '创建时间';

INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (2, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-23 07:59:59', '2020-03-23 15:27:46.000000', 4344966);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (3, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-23 15:59:59', '2020-03-23 16:05:04.000000', 4344967);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (4, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-23 23:59:59', '2020-03-24 00:05:05.000000', 4344968);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (5, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-24 07:59:59', '2020-03-24 08:05:05.000000', 4344969);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (6, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-24 15:59:59', '2020-03-24 16:05:05.000000', 4401793);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (7, '中压开关设备', '35kV', 'A001', 'I段', 9.3367, '2020-03-24 23:59:59', '2020-03-25 00:05:05.000000', 4425765);
INSERT INTO MAXIMO.RE_VOLTAGE_CONDITION (REVOLTAGECONDITIONID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, VOLTAGECONDITION, TIMEPOINT, CREATETIME, ROWSTAMP) VALUES (8, '中压开关设备', '35kV', 'A001', 'I段', 12.1084, '2020-03-25 15:59:59', '2020-03-25 16:05:04.000000', 4477750);
create table RE_VOLTAGE_EM_COMP_QUARTER
(
    REVOLTAGEEMCOMPQUARTERID BIGINT
        primary key,
    IEDNAME                  VARGRAPHIC(100),
    ASSETYPE                 VARGRAPHIC(100),
    PRODUCTMODEL             VARGRAPHIC(100),
    LOCATION                 VARGRAPHIC(100),
    PRODUCTMODELC            VARGRAPHIC(100),
    ELECTRICDEGREE           DECIMAL(31, 4),
    CREATETIME               VARGRAPHIC(100),
    COMPARISON               VARGRAPHIC(50),
    RATIO                    DECIMAL(8, 4),
    ROWSTAMP                 BIGINT not null
);

comment on table RE_VOLTAGE_EM_COMP_QUARTER is '中压设备-季度总电度量比对';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.REVOLTAGEEMCOMPQUARTERID is '主键';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.IEDNAME is '设备编码';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.LOCATION is '位置';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.ELECTRICDEGREE is '总电度量';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.CREATETIME is '时间-季度';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.COMPARISON is '对比结果';

comment on column RE_VOLTAGE_EM_COMP_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_VOLTAGE_EM_COMP_QUARTER (REVOLTAGEEMCOMPQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ELECTRICDEGREE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 13.0000, '2020-1', '有所提升', 0.0833, 5227767);
create table RE_VOLTAGE_EM_COMP_YEAR
(
    REVOLTAGEEMCOMPYEARID BIGINT
        primary key,
    IEDNAME               VARGRAPHIC(100),
    ASSETYPE              VARGRAPHIC(100),
    PRODUCTMODEL          VARGRAPHIC(100),
    LOCATION              VARGRAPHIC(100),
    PRODUCTMODELC         VARGRAPHIC(100),
    ELECTRICDEGREE        DECIMAL(31, 4),
    CREATETIME            VARGRAPHIC(100),
    COMPARISON            VARGRAPHIC(50),
    RATIO                 DECIMAL(8, 4),
    ROWSTAMP              BIGINT not null
);

comment on table RE_VOLTAGE_EM_COMP_YEAR is '中压设备-年度度总电度量比对';

comment on column RE_VOLTAGE_EM_COMP_YEAR.REVOLTAGEEMCOMPYEARID is '主键';

comment on column RE_VOLTAGE_EM_COMP_YEAR.IEDNAME is '设备编码';

comment on column RE_VOLTAGE_EM_COMP_YEAR.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_EM_COMP_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_EM_COMP_YEAR.LOCATION is '位置';

comment on column RE_VOLTAGE_EM_COMP_YEAR.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_EM_COMP_YEAR.ELECTRICDEGREE is '总电度量';

comment on column RE_VOLTAGE_EM_COMP_YEAR.CREATETIME is '时间-年度';

comment on column RE_VOLTAGE_EM_COMP_YEAR.COMPARISON is '对比结果';

comment on column RE_VOLTAGE_EM_COMP_YEAR.RATIO is '变化率';

INSERT INTO MAXIMO.RE_VOLTAGE_EM_COMP_YEAR (REVOLTAGEEMCOMPYEARID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ELECTRICDEGREE, CREATETIME, COMPARISON, RATIO, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 16.0000, '2020', '有所提升', 0.0666, 5228644);
create table RE_VOLTAGE_EM_QUARTER
(
    REVOLTAGEEMQUARTERID   BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    PRODUCTMODELC          VARGRAPHIC(100),
    ACTIVEELECTRICDEGREE   DECIMAL(31, 4),
    REACTIVEELECTRICDEGREE DECIMAL(31, 4),
    COLTIME                VARGRAPHIC(50),
    TIMEPOINT              VARGRAPHIC(50),
    CREATETIME             VARGRAPHIC(50),
    ELECTRICDEGREE         DECIMAL(31, 4),
    REACTIVEPERCENT        DECIMAL(31, 4),
    OPINION                VARGRAPHIC(50),
    ROWSTAMP               BIGINT not null
);

comment on table RE_VOLTAGE_EM_QUARTER is '中压设备季度有功电度量和无功电度量';

comment on column RE_VOLTAGE_EM_QUARTER.IEDNAME is '设备编码';

comment on column RE_VOLTAGE_EM_QUARTER.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_EM_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_EM_QUARTER.LOCATION is '位置';

comment on column RE_VOLTAGE_EM_QUARTER.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_EM_QUARTER.ACTIVEELECTRICDEGREE is '有功电度量';

comment on column RE_VOLTAGE_EM_QUARTER.REACTIVEELECTRICDEGREE is '无功电度量';

comment on column RE_VOLTAGE_EM_QUARTER.COLTIME is '采集时间';

comment on column RE_VOLTAGE_EM_QUARTER.TIMEPOINT is '处理时间';

comment on column RE_VOLTAGE_EM_QUARTER.CREATETIME is '时间-季度';

comment on column RE_VOLTAGE_EM_QUARTER.ELECTRICDEGREE is '总电度量';

comment on column RE_VOLTAGE_EM_QUARTER.REACTIVEPERCENT is '无功电度量占总电度比例';

comment on column RE_VOLTAGE_EM_QUARTER.OPINION is '意见';

INSERT INTO MAXIMO.RE_VOLTAGE_EM_QUARTER (REVOLTAGEEMQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, COLTIME, TIMEPOINT, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION, ROWSTAMP) VALUES (3, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 0.0000, 0.0000, '2020-03-20 17:33:58', '2020-03-25 14:06:16', '2019-4', 12.0000, 0.1100, '合理', 5229522);
INSERT INTO MAXIMO.RE_VOLTAGE_EM_QUARTER (REVOLTAGEEMQUARTERID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, COLTIME, TIMEPOINT, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION, ROWSTAMP) VALUES (4, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 2.0000, '2020-03-20 17:33:58', '2020-03-20 17:33:58', '2020-1', 13.0000, 0.0900, '合理', 5229523);
create table RE_VOLTAGE_EM_YEAR
(
    REVOLTAGEEMYEARID      BIGINT
        primary key,
    IEDNAME                VARGRAPHIC(100),
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    PRODUCTMODELC          VARGRAPHIC(100),
    ACTIVEELECTRICDEGREE   DECIMAL(31, 4),
    REACTIVEELECTRICDEGREE DECIMAL(31, 4),
    COLTIME                VARGRAPHIC(50),
    TIMEPOINT              VARGRAPHIC(50),
    CREATETIME             VARGRAPHIC(50),
    ELECTRICDEGREE         DECIMAL(31, 4),
    REACTIVEPERCENT        DECIMAL(31, 4),
    OPINION                VARGRAPHIC(50),
    ROWSTAMP               BIGINT not null
);

comment on table RE_VOLTAGE_EM_YEAR is '中压设备年度有功电度量和无功电度量';

comment on column RE_VOLTAGE_EM_YEAR.REVOLTAGEEMYEARID is '主键';

comment on column RE_VOLTAGE_EM_YEAR.IEDNAME is '设备编码';

comment on column RE_VOLTAGE_EM_YEAR.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_EM_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_EM_YEAR.LOCATION is '位置';

comment on column RE_VOLTAGE_EM_YEAR.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_EM_YEAR.ACTIVEELECTRICDEGREE is '有功电度量';

comment on column RE_VOLTAGE_EM_YEAR.REACTIVEELECTRICDEGREE is '无功电度量';

comment on column RE_VOLTAGE_EM_YEAR.COLTIME is '采集时间';

comment on column RE_VOLTAGE_EM_YEAR.TIMEPOINT is '处理时间';

comment on column RE_VOLTAGE_EM_YEAR.CREATETIME is '时间-年度';

comment on column RE_VOLTAGE_EM_YEAR.ELECTRICDEGREE is '总电度量';

comment on column RE_VOLTAGE_EM_YEAR.REACTIVEPERCENT is '无功电度量占总电度量';

comment on column RE_VOLTAGE_EM_YEAR.OPINION is '意见';

INSERT INTO MAXIMO.RE_VOLTAGE_EM_YEAR (REVOLTAGEEMYEARID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, COLTIME, TIMEPOINT, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 0.0000, 0.0000, '2020-03-20 18:14:25', '2020-03-25 08:00:05', '2019', 15.0000, 0.1000, '合理', 5230402);
INSERT INTO MAXIMO.RE_VOLTAGE_EM_YEAR (REVOLTAGEEMYEARID, IEDNAME, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, ACTIVEELECTRICDEGREE, REACTIVEELECTRICDEGREE, COLTIME, TIMEPOINT, CREATETIME, ELECTRICDEGREE, REACTIVEPERCENT, OPINION, ROWSTAMP) VALUES (2, 'AH01', '中压开关设备', '35kV', 'A001', 'I段', 1.0000, 1.0000, '2020-03-20 18:14:25', '2020-03-25 08:00:05', '2020', 16.0000, 0.0800, '合理', 5230403);
create table RE_VOLTAGE_POWERFACTOR
(
    REVOLTAGEPOWERFACTORID BIGINT
        primary key,
    ASSETYPE               VARGRAPHIC(100),
    PRODUCTMODEL           VARGRAPHIC(100),
    LOCATION               VARGRAPHIC(100),
    PRODUCTMODELC          VARGRAPHIC(100),
    POWERFACTOR            DECIMAL(8, 4),
    TIMEPOINT              VARGRAPHIC(50),
    CREATETIME             VARGRAPHIC(50)
);

comment on table RE_VOLTAGE_POWERFACTOR is '平均功率因数表';

comment on column RE_VOLTAGE_POWERFACTOR.REVOLTAGEPOWERFACTORID is '主键';

comment on column RE_VOLTAGE_POWERFACTOR.ASSETYPE is '设备类别';

comment on column RE_VOLTAGE_POWERFACTOR.PRODUCTMODEL is '设备型号';

comment on column RE_VOLTAGE_POWERFACTOR.LOCATION is '位置';

comment on column RE_VOLTAGE_POWERFACTOR.PRODUCTMODELC is '段信息';

comment on column RE_VOLTAGE_POWERFACTOR.POWERFACTOR is '平均功率因数';

comment on column RE_VOLTAGE_POWERFACTOR.TIMEPOINT is '采集点';

comment on column RE_VOLTAGE_POWERFACTOR.CREATETIME is '时间';

INSERT INTO MAXIMO.RE_VOLTAGE_POWERFACTOR (REVOLTAGEPOWERFACTORID, ASSETYPE, PRODUCTMODEL, LOCATION, PRODUCTMODELC, POWERFACTOR, TIMEPOINT, CREATETIME) VALUES (1, '中压开关设备', '35kV', 'A001', 'I段', 0.7653, '2020-03-24 07:59:59', '2020-03-24 10:44:58');
create table RE_VOLTAGE_TEMPERATURE
(
    REVOLTAGETEMPERATUREID  BIGINT
        primary key,
    IEDNAME                 VARGRAPHIC(100),
    AUPPERARMTEMPERATUREAVG DECIMAL(31, 4),
    BUPPERARMTEMPERATUREAVG DECIMAL(31, 4),
    CUPPERARMTEMPERATUREAVG DECIMAL(31, 4),
    AUPPERARMTEMPERATUREMAX DECIMAL(31, 4),
    BUPPERARMTEMPERATUREMAX DECIMAL(31, 4),
    CUPPERARMTEMPERATUREMAX DECIMAL(31, 4),
    ALOWERARMTEMPERATUREAVG DECIMAL(31, 4),
    BLOWERARMTEMPERATUREAVG DECIMAL(31, 4),
    CLOWERARMTEMPERATUREAVG DECIMAL(31, 4),
    ALOWERARMTEMPERATUREMAX DECIMAL(31, 4),
    BLOWERARMTEMPERATUREMAX DECIMAL(31, 4),
    CLOWERARMTEMPERATUREMAX DECIMAL(31, 4),
    ACABLETEMPERATUREAVG    DECIMAL(31, 4),
    BCABLETEMPERATUREAVG    DECIMAL(31, 4),
    CCABLETEMPERATUREAVG    DECIMAL(31, 4),
    ACABLETEMPERATUREMAX    DECIMAL(31, 4),
    BCABLETEMPERATUREMAX    DECIMAL(31, 4),
    CCABLETEMPERATUREMAX    DECIMAL(31, 4),
    TIMEPOINT               VARGRAPHIC(50),
    CREATETIME              TIMESTAMP(6)
);

INSERT INTO MAXIMO.RE_VOLTAGE_TEMPERATURE (REVOLTAGETEMPERATUREID, IEDNAME, AUPPERARMTEMPERATUREAVG, BUPPERARMTEMPERATUREAVG, CUPPERARMTEMPERATUREAVG, AUPPERARMTEMPERATUREMAX, BUPPERARMTEMPERATUREMAX, CUPPERARMTEMPERATUREMAX, ALOWERARMTEMPERATUREAVG, BLOWERARMTEMPERATUREAVG, CLOWERARMTEMPERATUREAVG, ALOWERARMTEMPERATUREMAX, BLOWERARMTEMPERATUREMAX, CLOWERARMTEMPERATUREMAX, ACABLETEMPERATUREAVG, BCABLETEMPERATUREAVG, CCABLETEMPERATUREAVG, ACABLETEMPERATUREMAX, BCABLETEMPERATUREMAX, CCABLETEMPERATUREMAX, TIMEPOINT, CREATETIME) VALUES (1, 'AH01', 1.0031, 0.9703, 0.9601, 37.9700, 35.4480, 34.9310, 0.9948, 0.9641, 0.9655, 37.9840, 35.4210, 34.9480, 1.0066, 0.9696, 0.9625, 37.9660, 35.4630, 34.9510, '2020-04-02 07:59:59', '2020-04-02 15:14:39.579000');