create table RE_TOTAL_COMPARE_QUARTER
(
    RETOTALCOMPAREQUARTERID BIGINT
        primary key,
    ASSETYPE                VARGRAPHIC(100),
    PRODUCTMODEL            VARGRAPHIC(100),
    LOCATION                VARGRAPHIC(100),
    SCORE                   DECIMAL(8, 4),
    CREATETIME              VARGRAPHIC(100),
    COMPARISON              VARGRAPHIC(50),
    RATIO                   DECIMAL(8, 4)
);

comment on table RE_TOTAL_COMPARE_QUARTER is '总体季度对比';

comment on column RE_TOTAL_COMPARE_QUARTER.RETOTALCOMPAREQUARTERID is '主键';

comment on column RE_TOTAL_COMPARE_QUARTER.ASSETYPE is '设备类别';

comment on column RE_TOTAL_COMPARE_QUARTER.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_COMPARE_QUARTER.LOCATION is '位置';

comment on column RE_TOTAL_COMPARE_QUARTER.SCORE is '评分';

comment on column RE_TOTAL_COMPARE_QUARTER.CREATETIME is '季度时间';

comment on column RE_TOTAL_COMPARE_QUARTER.COMPARISON is '对比结果';

comment on column RE_TOTAL_COMPARE_QUARTER.RATIO is '变化率';

INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO) VALUES (2, '中压开关设备', '35kV', 'A001', 4.3000, '2020-2', '有所下降', -0.1691);
INSERT INTO MAXIMO.RE_TOTAL_COMPARE_QUARTER (RETOTALCOMPAREQUARTERID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME, COMPARISON, RATIO) VALUES (3, '中压开关设备', '35kV', 'A001', 5.1755, '2020-1', '', 0.0000);