create table RE_TOTAL_SCORE_YEAR
(
    RETOTALSCOREYEARID BIGINT
        primary key,
    ASSETYPE           VARGRAPHIC(100),
    PRODUCTMODEL       VARGRAPHIC(100),
    LOCATION           VARGRAPHIC(100),
    SCORE              DECIMAL(8, 4),
    CREATETIME         VARGRAPHIC(100)
);

comment on table RE_TOTAL_SCORE_YEAR is '总体年度评分';

comment on column RE_TOTAL_SCORE_YEAR.RETOTALSCOREYEARID is '主键';

comment on column RE_TOTAL_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_TOTAL_SCORE_YEAR.PRODUCTMODEL is '设备型号';

comment on column RE_TOTAL_SCORE_YEAR.LOCATION is '位置';

comment on column RE_TOTAL_SCORE_YEAR.SCORE is '评分';

comment on column RE_TOTAL_SCORE_YEAR.CREATETIME is '时间-年度';

INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (1, '中压开关设备', '35kV', 'A001', 4.7377, '2020');
INSERT INTO MAXIMO.RE_TOTAL_SCORE_YEAR (RETOTALSCOREYEARID, ASSETYPE, PRODUCTMODEL, LOCATION, SCORE, CREATETIME) VALUES (2, '中压开关设备', '35kV', 'A001', 3.5000, '2019');