create table RE_SCORE_YEAR
(
    REMEDIUMVOLTAGESCOREYEARID BIGINT
        primary key,
    IEDNAME                    VARGRAPHIC(100),
    ASSETYPE                   VARGRAPHIC(100),
    SCORE                      DECIMAL(8, 4),
    CREATETIME                 VARGRAPHIC(100),
    ROWSTAMP                   BIGINT not null
);

comment on table RE_SCORE_YEAR is '年度评分表';

comment on column RE_SCORE_YEAR.IEDNAME is '设备编码';

comment on column RE_SCORE_YEAR.ASSETYPE is '设备类别';

comment on column RE_SCORE_YEAR.SCORE is '得分';

comment on column RE_SCORE_YEAR.CREATETIME is '年度时间';

INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP) VALUES (1, 'AH01', '中压开关设备', 50.0000, '2020', 3708764);
INSERT INTO MAXIMO.RE_SCORE_YEAR (REMEDIUMVOLTAGESCOREYEARID, IEDNAME, ASSETYPE, SCORE, CREATETIME, ROWSTAMP) VALUES (2, 'AH01', '中压开关设备', 51.0000, '2019', 3708765);